### ISSUE TITLE
php errors are not shown

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#108]
Hi,

I am using the latest commit or at least a recent one and I am building a module. If I forget a ; in the php code no error and  no system event  are generated.

"Should PHP/SQL error messages be shown on the screen" is set to "Show on screen"

I am running this on MAMP, php 5.4.4

You can test this by creating a new module that includes a file
`require_once($modx->config['base_path'] . "assets/modules/test/test.php");`

and in test.php 

just put 

```
<?php
echo "test1"
```

Thanks

**Comment by TimGS** [comment]
Fixed on TimGS/ClipperCMS.

Also need to consider the deprecated functions setting. Will push to the main repo once I've done this.
