### ISSUE TITLE
Short of calling the event OnManagerChangePassword

### ISSUE THREAD

**Issue by AgelxNash** [ClipperCMS/ClipperCMS#11]
The file is missing _/manager/processors/save_password.processor.php_ event call **OnManagerChangePassword**
<code>
$modx->invokeEvent("OnManagerChangePassword", array (
"userid" => $id,
"username" => $newusername,
"userpassword" => $newpassword
));
</code>
For example: _/manager/processors/save_user.processor.php_

**Comment by TimGS** [comment]
Fixed. Thanks.
