### ISSUE TITLE
KCFinder - File Browser

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#114]
KCFinder could be the next file browser for ClipperCMS, see this: http://www.clippercms.com/forum/index.php?topic=86.msg339#msg339

There is already an integration (http://narod.ru/disk/57883429001.94d112c2667d33a9c197ef9d83ae88f1/kcfinder.zip.html) but it doesn't use the manager language (AFAIK it's hardcoded to use always the english language).

**Comment by TimGS** [comment]
Integrated into develop.

**Comment by bossloper** [comment]
Just tried KCFinder in the latest development branch. A quick look... fine in Chrome, but in IE10 the right-side pane wraps below the left and so buttons and right pane are not visible.
![kcfinder-ie10](https://f.cloud.github.com/assets/1744687/239825/f60101a4-88d2-11e2-9966-e985a1e10122.png)

**Comment by TimGS** [comment]
I'll make a new issue for this. Thanks.
