### ISSUE TITLE
Jot - Improvements

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#115]
A lot of improvements for Jot, see this: http://www.clippercms.com/forum/index.php?topic=85.msg338#msg338

There is the need to test the new version and make sure that this will not break existing websites.
Also, I think that there is the need to translate some files from russian to english.

**Comment by TimGS** [comment]
Is this backwards compatible with Jot?

**Comment by microcipcip** [comment]
I need to test it. I will report back.

**Comment by TimGS** [comment]
It would be good if Jot had a decent anti-spam solution using an online service such as http://www.stopforumspam.com/.

See also http://forums.modx.com/thread/81517/comment-spam-in-the-demo-mini-blog-howto-article/#dis-post-449718

-- Tim.
