### ISSUE TITLE
New name for forked Eform

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#122]

**Comment by microcipcip** [comment]
FormBuilder ?

**Comment by nick0** [comment]
Reform   ?

Former   ?

FormIt  ?

Formal  ?

Informed  ?

Informer  ?

Inform  ?

Formed  ?

Formalize  ?

**Comment by Cipa** [comment]
Form Helper

**Comment by TimGS** [comment]
MailForm?

(EForm is AFAIK primarily designed for converting form submissions to emails.)

**Comment by Dmi3yy** [comment]
just  simple   "form"  or "Form"

**Comment by kp52** [comment]
I like Inform - which now has twice as many votes as any other suggestion! Could be seen as contraction of Input Form, and implies major use on contact pages.

**Comment by microcipcip** [comment]
I like simply "Form", as suggested by dmi3yy. Or maybe "cForm", where C stand for the initial of ClipperCMS.

**Comment by kp52** [comment]
There's a problem with generic names for specific features - ambiguity when you're also dealing with FORM tags, for instance. And though we're just looking at renaming eForm for now, there are plenty of reasons why some other snippet, module or whatever that does a more general job of building or handling forms might have a better claim to "Form" as its name.

**Comment by TimGS** [comment]
I agree with kp52. eForm isn't actually that generic a form builder and as such a generic name such as 'Form' - or even a minor variation - seems inappropriate.

Whilst it does have hooks for doing general jobs, it's designed for emailing out form submissions. If you've had to do anything more general purpose than that, you'll realise how hacky the solutions are for making eForm do what you want (or put another way, you probably shouldn't be using eForm in such cases).

It's primarily a form mailing solution - I think any name should reflect this.

**Comment by microcipcip** [comment]
I like MailForm.

**Comment by TimGS** [comment]
For info, suggestions so far with more than one advocate include:

1) Form
2) Inform
3) Mailform

**Comment by TimGS** [comment]
We are not updating Eform now beyond any updates issued by MODx, so this issue is now n/a.
