### ISSUE TITLE
Modx Carbon theme

### ISSUE THREAD

**Issue by fourroses666** [ClipperCMS/ClipperCMS#125]
Just did an upgrade to Clipper 1.1 and noticed I can pick Modx Carbon theme.
Shouldn't that one be removed?

**Comment by TimGS** [comment]
Ah - yes, I'm guessing it doesn't work properly now (?).

I'm not sure if the installer can wipe the old themes, but we could issue a warning to do so.

**Comment by fourroses666** [comment]
The dashboard is blank with that theme but further all works I think. I dunno if its possible ;p\* 

*to remove it

**Comment by TimGS** [comment]
I've just ensured that themes starting 'modx' cannot be selected.
