### ISSUE TITLE
SELECT TV from template blank (id=0)

### ISSUE THREAD

**Issue by AgelxNash** [ClipperCMS/ClipperCMS#128]
<code>SELECT tv.*, IF(tvc.value!='',tvc.value,tv.default_text) as value ........ WHERE template=...</code>
Line 1214 in manager/includes/document.parser.class.inc.php 
Line 2386 in manager/includes/document.parser.class.inc.php
Line 2520 in manager/includes/document.parser.class.inc.php
Line 183 in manager/processors/save_content.processor.php
may be more...

I think this SQL query to wrap up in <code>if($template>0) {
//SQL here
}</code>

**Comment by TimGS** [comment]
Is this to avoid running the SQL query for documents with no template?

I can't think of ever having documents with no template - but I appreciate that other developers may do things differently. Have you some examples?

Thanks.

**Comment by bossloper** [comment]
"I can't think of ever having documents with no template" 
An RSS feed document does not have a template. Any sort of Google site map would likely not have one either.

**Comment by TimGS** [comment]
All my site's XML (including RSS) feeds have a template containing the Ditto/List call. I am guessing you are instead using the content field for this? I steer clear of putting _any_ logic in any content field, but as above "I appreciate that other developers may do things differently."

(Note also http://www.clippercms.com/forum/feature-requests/proposal-rss-feeds/)

**Comment by TimGS** [comment]
I'll implement the check though.

**Comment by bossloper** [comment]
Yes, sounds a good idea not to use the content field for logic. I think it was the demo MODx installation for the RSS feed setup at some point, so got swept up from that.

**Comment by TimGS** [comment]
I've implemented this in DocumentParser::getDocumentObject() - the first quoted instance in document.parser.class.inc.php.

I can't see the other instances in document.parser.class.inc.php being worthwhile - but am willing to be persuaded with examples.
