### ISSUE TITLE
disable tinymce

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#133]
I used to be able to disable tinymce from the settings tab of document. I can't seem to find this setting anymore.

Thx

**Comment by TimGS** [comment]
Check the demo ManagerManager rules.

I think I hid it on the basis that most users would want TinyMCE for the richtext content.

**Comment by Cipa** [comment]
If this is the case maybe we should move some of these settings outside MM at some point. Maybe a core module like Doc Manager that allows hiding renaming different elements of the manager

**Comment by TimGS** [comment]
Possibly. I'd also intended at some point to offer multiple ManagerManager chunks on install, with at least once designed for novice users, and a near-blank one for advanced users.
