### ISSUE TITLE
Homonyms in the roles of managers

### ISSUE THREAD

**Issue by AgelxNash** [ClipperCMS/ClipperCMS#14]
![Homonyms in the roles of managers](http://agel-nash.ru/img/modx-manager-roles.png)

**Comment by yama** [comment]
https://github.com/modxcms-jp/evolution-jp/commit/97a6fed783c4986c8b0bbf29cce4da8f5efaffee

**Comment by AgelxNash** [comment]
good

**Comment by TimGS** [comment]
Fixed. Thanks.
