### ISSUE TITLE
ListIndexer needs updating to elimate mysql_data_seek()

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#141]

**Comment by microcipcip** [comment]
What does it do exactly? Is it like Ditto/List?

**Comment by TimGS** [comment]
It says it lists 'recent documents'. Its on the sample site. I've never used it anywhere else.

As an alternative, we could just dump it from the default install. The sample site needs updating anyway, and as previously discussed could be simplified to just use more 'standard' snippets. It is a minor pain having to deal with miscellaneous snippets such as this in the default install.

Note that the update to mysqli retains mysql as an option (although currently it's the other way round - mysql is the default and mysqli is an option; it may have to stay as such until AjaxSearch is updated to use the DBAPI). Put another way, there are two DBAPIs, mysql and mysqli. Only one is used at any time. As such old snippets such as this one that use direct mysql_\* calls instead of the DBAPI ($modx->db->*) can use mysql as before.

**Comment by kp52** [comment]
I would vote for removal from the standard installation. It's the sort of thing that you might _want_, but would rarely class as a _need_. And the idea does smack a bit of a date "hey look, we got us a website!" approach.

**Comment by microcipcip** [comment]
I would vote for removal as well. I have never used it and I have never seen anybody in the forum mentioning it. I didn't even know about that snippet till now.

**Comment by Cipa** [comment]
same here

**Comment by TimGS** [comment]
Removed!
