### ISSUE TITLE
Identical names in web & manager user group

### ISSUE THREAD

**Issue by AgelxNash** [ClipperCMS/ClipperCMS#15]
If you try to create a group of users (whether web or manager) of the same name appears on the screen parser error 

> Execution of a query to the database failed - Duplicate entry '*******' for key 'name'

**Comment by yama** [comment]
![pict](http://kura2.photozou.jp/pub/550/280550/photo/146735896_org.v1344097924.png)
This point?

https://github.com/modxcms-jp/evolution-jp/commit/5737b612591a9f677684234a28d46e675990d159
I send this code to ClipperCMS, later...

**Comment by AgelxNash** [comment]
Yes. It was about this error and I was saying.

**Comment by TimGS** [comment]
I've temporarily used INSERT IGNORE. This will have to change if non-MYSQL RBDMS are to be supported but will suffice for the moment.
