### ISSUE TITLE
Update ManagerManager for new manager HTML

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#155]

**Comment by Cipa** [comment]
We have to wait until we integrate Salvatore's theme. Once we have a stable
theme we can go ahead and do this

**Comment by TimGS** [comment]
The theme (as in manager/media/style/) should only affect the CSS and a very limited part of the HTML i.e. the login, welcome and manager lockout pages (not that I remember having ever seen the latter). As such ManagerManager's operation should be independent of themes.

**Comment by Cipa** [comment]
The html in the theme might change for example the wrappers and class names
around the pagetitle. this will affect at least the part where you can move
fields to new tabs

**Comment by TimGS** [comment]
I think we might be getting cross-wired over terminology. A 'theme' consists of all files in managar/media/styles/*/ (currently ClipperCarbon and ClipperModern).

The HTML in the manger/actions/\* pages may well change and MM is indeed dependent on this, though that's not part of the 'theme' in this sense. I don't think any of Savatore's work affects these files. It's probably entirely up to you what to do with the HTML in manager/actions/.

On a related note, theme CSS may have to change to cater for HTML changes in manager/actions/, but that's nothing to do with MM.

-- Tim.

**Comment by Cipa** [comment]
Just wanted to make sure we don't work on MM until the html is
stable(currently we're using tables but it will change to DIVs).

**Comment by TimGS** [comment]
OK

**Comment by Cipa** [comment]
Also removed any references to the export and keywords functionality

**Comment by Cipa** [comment]
sure
