### ISSUE TITLE
Moving checkbox TV to tab with ManagerManager

### ISSUE THREAD

**Issue by supaweb** [ClipperCMS/ClipperCMS#156]
When moving TV with type checkbox to another tab using ManagerManager rule _mm_moveFieldsToTab_ got an error "ManagerManager: An error has occurred: Error - Syntax error, unrecognized expression: [name^=tv4[]]:first". tv4 in a message is the id of TV. ClipperCMS 1.1, ManagerManager clipper-0.3.12

**Comment by supaweb** [comment]
Problem fixed with newer version of ManagerManager from here http://code.divandesign.ru/modx/managermanager

**Comment by TimGS** [comment]
We are having to fork ManagerManager to cope with HTML changes in the manager, but will look at this issue soon. 

Thanks.

**Comment by Cipa** [comment]
This doesn't seem to happen anymore for latest develop, should be closed
