### ISSUE TITLE
Insert & insert ignore

### ISSUE THREAD

**Issue by AgelxNash** [ClipperCMS/ClipperCMS#16]
Need to finalize [DBAPI::insert](https://github.com/ClipperCMS/ClipperCMS/blob/master/manager/includes/extenders/dbapi.mysql.class.inc.php#L211) for when you want to query the form INSERT IGNORE. On some projects, irrational use of a sequence of queries
<code>$q=$modx->db->select();
if($modx->db->getRecordCount($q));
$modx->db->insert();</code>
to prevent errors modx parser.

**Comment by TimGS** [comment]
How about DBAPI::replace instead?

**Comment by TimGS** [comment]
See https://github.com/ClipperCMS/ClipperCMS/commits/DBAPI (as yet untested)

**Comment by AgelxNash** [comment]
Good
