### ISSUE TITLE
develop: ClipperModern theme overwritten, so no login dialog

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#160]
in Develop branch, instprocessor.php (line 360) in /installer includes a database query that sets the 'manager_theme' setting to ClipperCarbon, overriding what is set in the setup.sql file (ClipperModern, ll 1144-1146).

There's no ClipperCarbon folder under manager/media/style, so you get a blank screen when you complete installation instead of the manager login dialog.

Cure: delete the query in instprocessor.php (mysql_query("REPLACE INTO $dbase......)

**Comment by microcipcip** [comment]
This seems the same error: http://www.clippercms.com/forum/manager/fresh-install-upload-new-manager-style-logout-and-blank-manager/

**Comment by fourroses666** [comment]
Ah yea this is the same problem. Can't find where to fix it.

**Comment by microcipcip** [comment]
You can rename the folder "manager/media/style/ClipperModern" to "manager/media/style/ClipperCarbon".

**Comment by fourroses666** [comment]
I had a custom style called ScienceStyle. Seems all it needs is html map with:

login.html
manager.lockout.html
welcome.html

**Comment by TimGS** [comment]
Fixed, I hope....
https://github.com/ClipperCMS/ClipperCMS/commit/9987dbff62760ae456b22f7eea25f6ca2a55992c
