### ISSUE TITLE
ClipperModern theme: top menu active area too small

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#161]
I find the active area of the Change Password, Help and Logout items in the top right menu of ClipperModern theme in the Develop branch very small - clickable only in the top 20% or so of the words. At first I thought the links were not active at all. The ClipperCarbon theme does not exhibit this behaviour.
Modern:
![modern-topmenu](https://f.cloud.github.com/assets/184620/80607/b630971a-6276-11e2-978a-96de179894df.png)
![modern-topmenu active](https://f.cloud.github.com/assets/184620/80608/bb32244a-6276-11e2-9b0e-4b6e6a9a991e.png)
Carbon:
![carbon-topmenu](https://f.cloud.github.com/assets/184620/80611/ea7050c4-6276-11e2-969a-02a9d3866f21.png)

**Comment by Cipa** [comment]
Same here but. Not sure what is it. Maybe the html has to reorganized

**Comment by microcipcip** [comment]
What browser and OS are you using? I don't see this problem on Firefox Win7.
It may be a problem with the z-index of #supplementalNav.

Edit: I haven't tried the develop version, I am going to test it now.

**Comment by Cipa** [comment]
Firefox Mac
Chrome Mac

**Comment by microcipcip** [comment]
#supplementalNav is not clickable because of "#Navcontainer #divNav {z-index: 2;}"
#supplementalNav needs: "#supplementalNav {position: relative; z-index: 3;}"

**Comment by Cipa** [comment]
works

**Comment by TimGS** [comment]
This problem occurs on the develop branch in Opera 12.
