### ISSUE TITLE
develop: "remember tab" setting doesn't remember

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#162]
Using the Develop branch, Manage Elements always goes back to the Templates tab when you exit the editing screen of an element, regardless of the Remember Tabs setting In the configuration settings.
Using the develop branch donwloaded 19 Jan, Windows 7, Apache 2.4, PHP 5.3.17, Firefox 17.0

**Comment by Cipa** [comment]
If you are talking about the develop-jquery branch(I think develop and jquery-develop  are the same at this point in time) than please check mine: https://github.com/Cipa/ClipperCMS/commits/develop-jquery

Not sure when Tim will have time to include it into the main develop branch

**Comment by kp52** [comment]
Will download from your repo and try. 
Note question about manager/actions/mutate_content.dynamic.php (typo?)

**Comment by Cipa** [comment]
fixed

**Comment by TimGS** [comment]
We can check this again on the next merger of develop-jquery with develop.

**Comment by TimGS** [comment]
I have the opposite problem in the current develop and develop-jquery branches. When this option is _not_ selected, the tabs are still remembered.

If it's easiest, I'd be quite happy to remove the setting and have the behaviour to always be 'remember tabs'.

-- Tim.

**Comment by Cipa** [comment]
I don't think my implementation uses that setting. I figured is not needed since the remember part is lost when you close the browser or window(don't remember which). 

Is this a user setting as well?

**Comment by nick0** [comment]
I think removing "the setting and have the behaviour to always be 'remember tabs'." is a great solution Tim.

Who wants to have it not remembered?

**Comment by microcipcip** [comment]
I don't think is a good idea to remove the setting. Sometimes remember tab can make you lose time because usually you want to edit the "General" tab setting. 

If, for example, I open a resource and go to a "Gallery" tab, it doesn't mean that the next time I open that resource or another resouce I want to go on that tab.

**Comment by kp52** [comment]
The tabs in question here are the  Manage Elements ones (Templates, Template Variables etc.), not the ones involved in editing resources. The General/Settings tabs selection has always been "sticky", I think (just checked on a MODX 1.0.4 site).

(Edit 25/2) Wrong! I had never associated behaviour of resource tabs with this setting, as it's always been the behaviour of the Manage Elements tabs that annoyed me. Now I see it extends to both areas, which is not so good, particularly when you go to a resource that doesn't even have the last tab you used. I'd rather the two kinds of tab were handled separately.

![manage-elements](https://f.cloud.github.com/assets/184620/188035/5e7b8408-7dba-11e2-9de5-c63bd8b8e785.PNG)
