### ISSUE TITLE
Issue with some .htaccess rules - 500 internal server error

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#173]
# Block directory listings

IndexIgnore *

Options +FollowSymlinks

**Comment by TimGS** [comment]
I found this http://forums.modx.com/?action=thread&thread=28117 about the latter issue.

**Comment by microcipcip** [comment]
Ok, should we close the issue then? Maybe it is server-releated.

**Comment by TimGS** [comment]
It certainly depends on the server config. The only issue is whether the server configs that give rise to this are frequent enough to consider.

IndexIgnore is for security. It's not essential and is new to 1.1.

Options +FollowSymlinks is needed for friendly URLs. There is probably more to lose by removing it than by keeping it.

**Comment by TimGS** [comment]
I've commented out the former and added a comment recommending it to be uncommented unless a server error results.
