### ISSUE TITLE
A more secure way to change the password

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#174]
When I go "Change password" in the top right corner I am not asked for my old password. This could be a problem in some cases and was wondering if we can strength the process by asking the old password. If you really want to change the pass cause you forgot the old one you should use the Forgot Pass functionality.

Not sure how this impacts the Edit user functionality. Maybe ask for your pass if you try to edit your own account.

PS: I'm not sure this is necessary. Might be to much trouble in the end.

**Comment by TimGS** [comment]
"I'm not sure this is necessary"... I think you may be right. You decide - if you decide to do nothing, label as 'wontfix' and close the issue.
