### ISSUE TITLE
Ditto config and custom extenders not transferred to List 

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#175]
If you have Ditto configurations and extenders in files in the Ditto folders, these are not available when you convert the site to Clipper. The custom files work fine once you copy them to the relevant locations in the List snippet folders.

Given that anyone using cofnig files and custom extenders can probably work thisout for themselves, this might be a matter for documentation rather than fixing.

**Comment by TimGS** [comment]
I'd be happy with this in the documentation. The CMS code will usually not have the permissions to move the files, and leaving the old 'ditto' folder intact is not efficient - thus the best solution is to manually move them.

As you say, if people are using these files, they won't be put off by having to move them.

**Comment by TimGS** [comment]
Shall I close this, and pass it over to the documentation department ;-) ?

**Comment by TimGS** [comment]
Bump - is this documented?

**Comment by kp52** [comment]
It is now! (http://www.clippercms.com/documentation/doc-extras/extras-bundled-snippets/snippets-list.html)
