### ISSUE TITLE
develop: $manager_theme with / or not

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#177]
$manager_theme has a / at the end. I don't think it was like this previously.
In some cases the paths are generated with //. See sysalert.display.inc.php
Will the end slash become standard?

**Comment by TimGS** [comment]
I don't think it should have the slash.

Do you know which file is causing it to gain the slash?

**Comment by Cipa** [comment]
I traced the slash to this code, present in a lot of action files

```
if ($manager_theme)
        $manager_theme .= '/';
else    $manager_theme  = '';
```

I don't think there is something we can do for now in sysalert.display.inc.php except remove the extra slash from where the css file is included

I will send send a pull request soon

**Comment by Cipa** [comment]
The problem is more complex. I think the best solution is to remove the code above from all the action files and redo the paths.

Currently these paths are wrong

href="media/style/ClipperModern//style.css"
href="media/style/ClipperModern//manager.css" />

But if I remove the // from header.inc all the other actions will break.

I am little confused about why the code above was used but I don't think is correct. Luckily browsers don't really care about //.

**Comment by TimGS** [comment]
Agreed - this needs to be consistent. Remove the code that appends the / in the action files and check all instances of $manager_theme in changed files.

I suspect that the original authors were making provision for an 'empty' manager theme that just used the /media/style/ directory itself - this is a bit messy though, if there is ever a 'default' theme it is best in a 'default' directory.

-- Tim.
