### ISSUE TITLE
develop: in some actions files style.css is included a second time + $theme_refresher

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#178]
This seems to be connected to the change theme functionality. I propose we move this variable in the header.inc.php where the style file is inserted or remove it completely.

If we remove it maybe we can find a browser API that could clear the cache but I could not find one. 

Currently I think removing it is not a bad idea as we only have one theme and I think this functionality should be implemented in a different way.

Here's the line I want to remove together with the theme_refresher var.
`<link type="text/css" rel="stylesheet" href="media/style/<?php echo $manager_theme?>style.css<?php echo '?'.$theme_refresher?>" />`

Any other opinions?

**Comment by TimGS** [comment]
It looks superfluous -  probably a relic from an earlier system that may not have even been ever implemented.

There is no need to clear the browser cache as different themes have different files.

All instances can be removed (including in setup.sql).

**Comment by TimGS** [comment]
Cipa - just checking - are you sorting this or shall I?

**Comment by Cipa** [comment]
I could try to do it tomorrow or Sunday.
If you have the time why not I haven't started yet

**Comment by TimGS** [comment]
Done.
