### ISSUE TITLE
Quick way to go to css file

### ISSUE THREAD

**Issue by fourroses666** [ClipperCMS/ClipperCMS#18]
Is there a way to go to the css directly? 
It takes many clicks to get there and would like to see some shortcut.

Perhaps somewhere in config u can direct to the file and when u are on the Filemanager there i a direct shortcut to it?
popup or not.

**Comment by AgelxNash** [comment]
Create a new document with the following parameters contentType = text/css
Replace the path to the CSS file in the [~ID_DOCUMENT~]

Or am I not understand you?

**Comment by fourroses666** [comment]
Let me try to explain :)

While I'm building a website I change my CSS file allot. To get there, and want to change (for example) my body fontsize, I have to click on Elements > Manage Files > assets / templates / mymap / css / file.css
That are a lot of clicks.

Wouldn't it be better if its possible to add a link on the Manage Files "rootpage" where u directly go to the css page.  That direct link can be add on the Tools > Configuration > Interface & Features.

When the link is placed it appears on the Elements > Manage Files page, like this:

Directory listing for:/

New Directory
To top level
Up one level
CSS file     <--

It's just an idea which came up, i would like it.

**Comment by TimGS** [comment]
The trouble with this is that is one specific solution for one way of working. I'm not convinced it would have widespread use.

My prefered way of working is to develop on a local machine. I have a text editor open with the css/js/whatever files I'm working on. There is no need for access via the CMS. Another way I sometimes work is on a remote machine with SSH access - in which case I have a terminal to the machine and nano (text editor) open with the relevant files. Again there is no need for file access via the CMS.

Even if I did access file via the File Manager, how many shortcuts would I want? I may have more than one CSS file. I may have IE specific CSS files, and I may want them in a separate directory. I may have JS files. I may have HTC files.... and so and so forth.

If I was in your situation with this way of working I would have an extra browser tab open with the modx/clipper file manager. No need to go there more than once per session as you just keep the CSS file open in that tab.

If you want a shortcut I would suggest a module - there is no need to modify the core. For example, to edit modx.css in the modxhost template the link is:

http://SITEURL/manager/index.php?a=31&mode=edit&path=FILEPATH_TO_SITE_ROOT%2Fassets%2Ftemplates%2Fmodxhost%2Fmodx.css#file_editfile

A module that redirects to this location would be sufficient. With some thought as to options a module could be developed to handle multiple files (not just CSS). This would be far better from adding to the core - and we are trying to avoid this wherever possible. We'll have a forum open soon (in the meantime sorry for the delay) where you can ask for support on such things.
