### ISSUE TITLE
Develop: MM: is there a field "log"

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#185]
The current mm_demo_rules has 

```
mm_hideFields('log');
```

I have no idea what this is. Can I remove it?

**Comment by kp52** [comment]
I think this is the "Enable Stats Tracking" checkbox in Settings, enabling you to mark pages for inclusion in or exclusion from your own tracker plugin. I would leave it in - some of the sites I look after have such low traffic it isn't worth getting all wired up for Google etc. tracking, but I'd still like to know where people are going.

**Comment by Cipa** [comment]
I have "Enable Stats Tracking" but the "log" did not show. Can you confirm on the develop branch?
Maybe I'm looking in the wrong location. I never used this.

**Comment by TimGS** [comment]
I'm going to look at the default MM chunks anyway - it's already down as another issue.

**Comment by kp52** [comment]
mm_hideFields('log'); hides the "Enable Stats Tracking" checkbox in a resource's Settings tab. The checkbox is the inverse of the '''donthit''' field in the site_content table. It doesn't do anything, it's just available for custom tracking plugins.

**Comment by Cipa** [comment]
I already started porting MM to jQuery UI but I won't touch the chunk.
Hope to have something ready soon
