### ISSUE TITLE
New config warning re LC_ALL

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#187]
Installed Develop from GitHub files updated today (3/3/13), and have a configuration warning I haven't spotted before: 
'Locale LC_ALL not set correctly'
What does this mean?
LC_ALL as defined in config.inc.php is not detected as being the current locale for LC_ALL.

There's no LC_ALL in my config.inc.php. Is this something to do with me using Windows/Apache as my test server? I haven't tried it on a Linux server yet.

**Comment by Cipa** [comment]
Happens on MAMP as well. Not sure what it is either but did not have to
look into it
php 5.4

**Comment by TimGS** [comment]
It's a new (and optional) feature to set locales in config.inc.php.

Have you done a fresh install (or upgrade) since pulling the new files from github?

**Comment by TimGS** [comment]
Ignore the above message. Now fixed.

See also https://github.com/ClipperCMS/ClipperCMS/issues/21
