### ISSUE TITLE
Develop: time to upgrade jquery and jquery ui to the latest, I think

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#189]
I would like to do this upgrade as soon as possible. Opinions?

jQuery 1.9.1
jQuery UI 1.10.1

**Comment by TimGS** [comment]
Go ahead.

**Comment by Cipa** [comment]
There is one issue. The new jQuery removed some deprecated functions to make the code smaller. How do you propose to integrate jquery-migrate-1.1.1.min.js. 

> The plugin restores deprecated features and behaviors so that older code will still run properly on jQuery 1.9 and later. 

Solutions:
- add the code to the jquery file
- add a new setting to the configuration area to enable the migrate plugin
- just add an API

Thanks

**Comment by TimGS** [comment]
Do we need any deprecated functions for the core?

**Comment by Cipa** [comment]
I don't know yet, some plugins/modules might require them as they are pretty old.

**Comment by TimGS** [comment]
I suggest looking through http://jquery.com/upgrade-guide/1.9/ to gauge how likely problems are. Nothing stands out as being something that I recognise seeing or using except jquery.browser which will require assets/snippets/webusers/js/jquery.corner2.js to be upgraded to the current version of jQuery corner.

Perhaps we should just upgrade jQuery and then check the core install. I doubt whether jQuery would release a new version that resulted in widespread problems for existing sites.

**Comment by TimGS** [comment]
On balance I'm now wondering whether to stick with jQuery 1.8 for Clipper 1.2. That should give to time to investigate whether the jquery-migrate-1.1.1.min.js plugin is really required.

Cipa - what do you think?

**Comment by Cipa** [comment]
We can stay on 1.8 until the next release, But I think we can upgrade
jQuery UI. I will look into it asap

**Comment by TimGS** [comment]
OK. I'll re-assign this issue to 1.3 - but do upgrade the UI for 1.2 anyway if you think it worthwhile.

**Comment by Cipa** [comment]
I upgraded to the lates jQuery UI. See my pull request

I also ran some jQuery migrate tests and except for 2 warnings everything looked good.
One warning was for Res Manager: jQuery.fn.live() is deprecated
The other was for the Search page: jQuery.fn.attr('selected') may use property instead of attribute

What we could do is append jquery migrate to the end of the latest jquery file and remove it later on. A year from now or something.

**Comment by TimGS** [comment]
I haven't got the pull request - but as we are about to release 1.2 perhaps we should wait till 1.3 now. Making significant changes this late in the day could easily create problems that don't surface until after release, simply because we haven't the time to test this update enough.

Reopening as 1.3 issue.

**Comment by TimGS** [comment]
@Cipa - can you sort this for 1.3 (develop branch). Thanks.

**Comment by Cipa** [comment]
not any time soon, maybe in 1 2 weeks

**Comment by TimGS** [comment]
@Cipa - what's the state of play with this? We can defer till 1.4 if you prefer. Your decision I think.
