### ISSUE TITLE
resource numbers: hiding docid numbers in lhs tree [originally included resetting numbers]

### ISSUE THREAD

**Issue by nick0** [ClipperCMS/ClipperCMS#19]
Hi Tim and Co,

I am so excited to see this development!

As a feature request:

a. The ability for admin users to reset resource numbers would be nice (eg in the instance where lots of pages have been deleted): I like using a master 'evo (soon to be clipper)' site when developing a new project to be more efficient. Once a new site is close to finished, I would love to be able to reset the document numbers. I would have no problems in manually adjusting internal links after resetting doc numbers.

b. It would be nice to be able to hide resource numbers in the LHS tree for non admin users - set either with ManagerManager or as a configuration setting. (the resource numbers seem to confuse some of my clients and clogs up the space).

Love your work.

**Comment by TimGS** [comment]
Hi,

(a) First question is why? It does have the potential to break all but the simplest sites. Most of the sites I've built in Evo, I wouldn't want to even have the facility to do this. If a client managed to do it (even if they normally have an 'Editor' role, most clients also need an admin id - once you sign off the site they will need this to give to any other future developer) then they would probably break their site, possibly withouth initially realising.

Second question is if you want it, why not implement it as an Extra? You could even automatically fix such as [~6~] in templates and chunks.

(b) Perhaps, we'll discuss this for 1.2

thanks,
Tim.

-- TIm.

**Comment by nick0** [comment]
Hi Tim,

a) Probably for neatness I guess. I have many demo pages etc numbering into the low one hundreds in my demo site it would be a nice feature to roll back the numbers. Clients breaking is not an issue, they don’t access configuration settings. I am not a coder so have no idea how to do that as an extra.

b) no worries thanks Tim. Implementing b) would probably overcome my need for a) so the client doesn’t see or get confused by the big range in doc id’s.

Thanks.

**Comment by TimGS** [comment]
OK. Issue assigned to milestone 1.2.

**Comment by microcipcip** [comment]
Sometimes when I build complex websites a) is useful because during the test I create lot of resources. It is also quite dangerous though, because if there are hardcoded IDs (very likely) you can break the website.

For b) sometimes you can do this with CSS but obviously it is not a good idea because developer can't see IDs during the development.

**Comment by TimGS** [comment]
I suggest we add a role permission for this. Admins always get to see the docids, on the assumption that they are either developers or people who won't be confused by numbers ;-), but the default Editor/Publisher roles do not get to see them, as they are probably not developers.

Its a fair point that non-developers have little use for docids. They certainly should have no need to hardcode docids into content. On the other hand, it is sometimes useful to unambiguously refer to a document during discussion - avoids issues with similarly titled documents, and documents getting renamed.

The other viable alternative that I see is having a button above the document tree for switching this (and maybe other options). As the backend site search has an id field and given my point above on ambiguity, this may be of use. By default in each session it is off, but can be switched on with a single click. We could even use localStorage to remember this setting between sessions. Hmm... I think I'm talking myself into preferring this option.

**Comment by nick0** [comment]
excellent, thanks Tim and microcipcip

role permission sounds great.

agreed, doc ids are not an issue for developers / admin users.
If needed, an editor can also easily find a doc id by hovering over a resource in the tree and seeing it in the resource info.

A button above the tree to toggle is also a nice idea (with your off by default and session cookie remembering sugesstions). That would be very quick for developers to check a number when building a site, and then give admin users the option to hide the id's in the tree if they prefer. I like it. I probably lean to this more also, unless there is a combo with a role permission which when turned on, hides the tree button from selected roles.

Love your work Tim

**Comment by TimGS** [comment]
I've implemented this as a config setting.

The default behaviour does not change. Optionally you can hide docids from non-admins.
