### ISSUE TITLE
Chrome - remove yellow outline

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#194]
On Clipper Develop Google Chrome shows a yellow outline every time you click a tab or a input field. Around line 251 of style.css we could add the following (see [reference code here](http://stackoverflow.com/questions/3397113/how-to-remove-border-outline-around-text-input-boxes-chrome)):
`*:focus { outline: none; }`

**Comment by TimGS** [comment]
Done.
