### ISSUE TITLE
Develop: No context menu in tree after first access

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#195]
I'm not getting any context menu in the resource tree in the current Develop version (7 March). I think this began after the jquery branch was merged.

The menu does appear just once, the first time it is accessed via the icon or a right-click on the title after login. (Appears a few times in Chrome before failing)

Firefox 18.0.1, IE9 64bit, Chrome 25,
Windows 7 Home Premium, Apache 2.4, PHP 5.4.11

**Comment by Cipa** [comment]
Fixed [here](https://github.com/Cipa/ClipperCMS/commit/3677171b0ddc6639d1c921c669bccf3717d8b4e5)

Tim, could you manually add this pls.

Thx

**Comment by TimGS** [comment]
Done.
