### ISSUE TITLE
Updated manager

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#2]
Eliminate mootools for jquery
Drag and Drop re-ordering
Eliminate Frames (?? long term ??)

**Comment by nick0** [comment]
drag and drop re-ordering in the tree would be sensational!

**Comment by fourroses666** [comment]
drag and drop +10000 

if I remember correct, Microcipcip had a demo where that worked?

**Comment by microcipcip** [comment]
It is just plain html, but yes, I did try: http://www.jertix.org/demo/modxmanager3/

**Comment by fourroses666** [comment]
Ah yea, thats the one!, it would be so nice to have that working. 

Dunno whats possible because of Evo's frameset and if the jp or ru versions of modx already have done the drag and drop but that would be a major + for Clipper.

**Comment by yama** [comment]
![tree](http://kura2.photozou.jp/pub/550/280550/photo/169343894_org.v1361020443.png)
I make a trial product. I think that this works in ClipperCMS.

**Comment by fourroses666** [comment]
:D :D :D great addition, would love to see this in Clipper.
