### ISSUE TITLE
Insert/Edit Image Window can be very small

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#202]
When editing a resource and selecting 'Insert/Edit Image' the popup window can sometimes be very small. It does not always seem to happen. I have seen the issue on IE10 and Chrome v25, but not on Firefox 18.0.2 ... yet.

I tend to use TinyMCE with 'inlinepopups' plugin, which works fine.

![image-window](https://f.cloud.github.com/assets/1744687/239852/875cfa5c-88d5-11e2-8a27-dd0d4668b4e8.png)

**Comment by Cipa** [comment]
Tested this in the latest IE10, both develop and stable branches and I could not reproduce this issue.
Unless further details are provided there's nothing I can do about IE.

Chrome is the only one with this problem.

**Comment by Cipa** [comment]
Update:
This seems to be the bug: http://www.tinymce.com/develop/bugtracker_view.php?id=5353

From the looks of it there are 2 solutions: update the code or use the inlinepopups plugin

Fix 1. Update the code. This ticket is still open at TinyMCE so maybe we can update the code with the patch here: https://github.com/tinymce/tinymce/pull/138
This is Chrome bug in the end so I am not sure what's the best thing to do, wait or patch

Fix 2. Go to Configuration/Interface & Features/TinyMCE Settings/Theme and select Custom Theme.
Add inlinepopups in the plugins field

**Comment by TimGS** [comment]
Are there any disadvantages to using inlinepopups?

Can we force every 'Theme' to use inlinepopups, or must it be a custom theme?

**Comment by Cipa** [comment]
I don't think there are any, from my tests everything was ok. I actually tend to prefer inline popups as it's not that messy. Lots of users seem to lose that pop-up window from time to time.

The only issue I see is that users might not use the default TinyMce configuration.

**Comment by bossloper** [comment]
If a line was added to tinymce.functions.php just before the build call (about line 123) then I think that would work for all configs:

```
    $plugins .=',inlinepopups'; // new line: force inlinepopups for all configurations
    $str  = $this->build_mce_init($params,$plugins,$buttons1,$buttons2,$buttons3,$buttons4);
```

Update. Or, even better add the line to the build_mce_init function to catch any 3rd party usage of TinyMCE.

**Comment by TimGS** [comment]
Sounds reasonable to force it - as long as we long as we don't do this by changing the files that come from TinyMCE itself (by this I mean the TinyMCE editor, not the TinyMCE plugin).

As such, editing anything in tinymce.functions.php should be fine.
