### ISSUE TITLE
KCFinder - Enhance interface to help file selection

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#203]
For KCFinder it may not be intuitive for some that you have to right click for a menu or double click on a file or image to select it for the editor.

Maybe either a message about double clicking and/or a 'select' button on the top toolbar?

**Comment by Pathologic** [comment]
It's possible to make 3 additional buttons on toolbar - to emulate left mouse button double click, right mouse button single click and ctrl key hold. Though, I see no sense in such feature, so what other participants think?

**Comment by TimGS** [comment]
Related question - Anyone tried kcfinder on a touch screen? Some of those mouse actions could be an issue.

**Comment by TimGS** [comment]
Anyone wish to make a firm proposal? Possibly it should be discussed in the forum but feel free to copy it here.

@bossloper?

**Comment by TimGS** [comment]
I've just checked, and there is a 'help' option now in the kcfinder menu. Possibly this is sufficient? I'm closing this issue, but feel free to reopen if you have a better proposal.
