### ISSUE TITLE
Reports -> View manager logs - Date drop-down not working

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#204]
The 'View manager logs' page under 'Reports' does not display the date drop-down for the 'from' or 'to' fields.
Tested in IE10, Firefox 18.0.2 with latest development branch.

**Comment by Cipa** [comment]
See #206

**Comment by TimGS** [comment]
@uxello Can you retest?

**Comment by bossloper** [comment]
Yes working now.

**Comment by TimGS** [comment]
Thanks.
