### ISSUE TITLE
Develop: mm.inc.php deletedcode reintroduced

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#205]
ManagerMananger code in mm.inc.php that was removed on 4 March (https://github.com/ClipperCMS/ClipperCMS/commit/a34b0d2863cb44d37421d10946bae17d82526e28#assets/plugins/managermanager/mm.inc.php) has reappeared in later commit (https://github.com/ClipperCMS/ClipperCMS/commit/c310ce8f7e657cde31e432866b433652d5ee5d81#assets/plugins/managermanager/mm.inc.php)

**Comment by TimGS** [comment]
Fixed.
