### ISSUE TITLE
develop: jquery plugins in assets/js

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#207]
I noticed a few jquery plugins in the assets/js folder. Were are they used and why

jquery.colorbox-min.js
- old version
- used by QM

jquery.form.js 
- really old version
- used by webusers

jquery.taconite.js 
- really old
- used by webusers

On top of that there is a loadingAnimation.gif that I don't think is used. I looked for anything mentioning this file but nothing came up

I'd like to start a discussion about updating these plugins and assign some tasks.

Thanks

**Comment by TimGS** [comment]
If there are new versions of each plugin, just update each file and make a pull request.

**Comment by Cipa** [comment]
All files have been updated
