### ISSUE TITLE
develop: HTML5 doctype for manager

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#208]
would like to upgrade the doctype to <!doctype html>

currently we have this:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
```

**Comment by TimGS** [comment]
If the manager HTML is valid HTML5 (is it?) then that's seems reasonable.

**Comment by Cipa** [comment]
From what I've seen the code is compatible with HTML5. From what I read
HTML5 is more permisible than HTML4 and XHTML so I don't expect any
problems even on older browsers.

**Comment by TimGS** [comment]
OK.

**Comment by Cipa** [comment]
I am wondering if we should add something like this. Currently I don't think it's needed but might be useful for older browser support

```
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
```

**Comment by Cipa** [comment]
Tim, I think we can close this

**Comment by TimGS** [comment]
Re-opened, because frames/1.php which contains the actual frame, needs (currently) to be in it's 'old' doctype to be valid (HTML5 doesn't include frames as valid elements).

Shall we revert 1.php to HTML4?

I think the contents of each frame can still be HTML5.

-- Tim.

**Comment by Cipa** [comment]
Relevant:
http://stackoverflow.com/questions/4846019/any-way-of-using-frames-in-html5

I honestly don't think it matters as long as the frames are properly
displayed

**Comment by microcipcip** [comment]
I agree with Cipa, I don't think this is going to be a problem.
