### ISSUE TITLE
setlocale

### ISSUE THREAD

**Issue by MPerrine** [ClipperCMS/ClipperCMS#21]
As french user, I've always had problem with setlocale. I need to create a plugin, on OnWebPageInit with : 

`setlocale (LC_TIME, 'fr_FR.utf8','fra');`

in order to get date in french

Would it be possible to make the language configured in manager, used on every page ?

**Comment by TimGS** [comment]
Currently there appears to be inconsistent use of setlocale(). It is used in:

assets/snippets/ditto/lang/russian-UTF8.inc.php
assets/snippets/ditto/lang/russian.inc.php
install/lang/russian-UTF8.inc.php
manager/includes/lang/russian-UTF8.inc.php
manager/includes/lang/spanish.inc.php
manager/includes/lang/russian.inc.php

It would be feasible and probably desirable to remove the latter three and have manager/index.php set the locale itself according to the config's manager language.

I suspect the install file's setlocale is superfluous but we can check this.

Regarding the front end, we could make it a config option. It should not duplicate the manager language as they may not be the same. We also need to have the option for it not to be used so developers of multi-language sites can set it accordingly in their own code as you are doing now (note that a multi-language extension to the core is in development).

The use of setlocale in the ditto files can be checked at the same time.

I will make this an issue to be addressed in 1.2, at the same time as the multi-language extension.

-- Tim.

**Comment by etal2** [comment]
When revising this please take into consideration that the locale affects url resolution when url aliases have international characters (think Japanese urls etc) . This happens very early in the request processing chain, before any of the existing events occur so setting the locale on OnWebPageInit does not help.

I opened a bug in the old modx bug tracker and had a patch that added another system event to allow setting the locale before resolving urls allowing to override the url resolution mechanism completely if needed. Unfortunately the code was lost when transitioning away from jira:
http://tracker.modx.com/issues/806

The Japanese modx solution is to have the locale set in the config file.

**Comment by TimGS** [comment]
I think it should go in the config file, if it is to be used.

We can either have an extra feature in the installer to select the locale from those available (on servers where we can detect these - which I think is dependent on PHP being able to use shell_exec('locales -a')) and write this to config.inc.php, or simply leave the developer to do this manually.

The problem with setting the locale in the installer is that many (most?) sites are not built on the server which they will eventually live on - and therefore we cannot be sure which locales are really going to be available. We don't want users who don't know about locales to have problems when they move the site to the live server. As such, if it is to be an installer option, the default should be to do nothing, with a strong warning for users who don't know what we are talking about, to select that option.

-- Tim.

**Comment by TimGS** [comment]
Added to develop.

setlocale() is optionally written to the config file. A check is also made on the welcome page of the manager that the locales are being set correctly - this caters for site moves across servers which have differing locales and also caters for hosts changing server locales.

If PHP is in safe mode then this option won't be available in the installer (I'm not aware of any way of obtaining all available locales except by using shell_exec()), but a knowledgeable coder can add the call to setlocale() manually. I don't see this as a huge problem - anyone who isn't knowledgeable enough to do this is unlikely to understand what locales are all about anyway.
