### ISSUE TITLE
Develop: TVs not working

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#210]
I'm finding with a fresh install from yesterday's or today's develop branch that TVs are simply producing no output. With basic no-sample site, I tried a simple Text TV, which produced nothing (checked with a snippet that the name is correct, value exists and TV is available on same page). Installing the sample site, there's no login form in the right-hand column.

TVs working normally in install of Clipper 1.1.1 in same environment.

Windows 7 Home Premium, Apache 2.4, PHP 5.4.11

**Comment by Cipa** [comment]
I can confirm this. A TV named TEST1 in my case is not displayed if I add it to the template like [_TEST1_].
No errors are reported. Not sure where the problem is.

**Comment by kp52** [comment]
Appears to be a bug in document.parser.inc.php function **getDocumentObject()** (line 1347)
Replacing function def with that from a 4th March version of develop branch makes TV values appear on cue.
??? KP

**Comment by TimGS** [comment]
Fixed, I hope.
