### ISSUE TITLE
Editing of welcome.static.php

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#212]
Before Clipper there was an hack of Evolution for editing, by using a chunk, the tabs and content of welcome.static.php page ([link](http://wiki.modxcms.com/index.php/Customizing_the_Manager_Homepage)). 

I like to add some custom buttons on the welcome screen (basically in the first tab, before the configuration tab). Is it possible to add this feature? As a temporary solution I have overwritten the welcome.static.php file but obviously this will means I will have to be careful when I upgrade the CMS.

**Comment by TimGS** [comment]
welcome.html (used by welcome.static.php) is now in the theme folder i.e. /manager/media/style/<theme folder>/html and can be changed without it being overwritten on upgrades _as long as you do this in a new theme_.

See also forum discussion.
