### ISSUE TITLE
Develop: QM hangs on Edit Resource

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#213]
Using 13 March edition of Develop and sample site, select Edit Resource from Quick Manager menu and screen hangs on "Please wait..." message.

Firebug console reports:
TypeError: $ is not a function
http://wsl/manager/index.php?a=27&id=244&quickmanager=1
Line 791

TypeError: $ is not a function
http://wsl/manager/index.php?a=27&id=244&quickmanager=1
Line 105

![qm-hang](https://f.cloud.github.com/assets/184620/258369/eb1e9196-8c94-11e2-9494-d1a005ffe83b.PNG)

**Comment by Cipa** [comment]
Fixed
https://github.com/ClipperCMS/ClipperCMS/pull/214
