### ISSUE TITLE
remove jquery noconflict from the manager

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#215]
I think we should remove jquery no conflict setting from the manager and from all the extras using it. I don't think there is a need for it since we're using only jquery

**Comment by TimGS** [comment]
Other people might not be using jQuery, so all code needs to be able to optionally use noConflict().

This mainly applies to frontend extras (I think QM needs checking) but could in theory apply to backend extras.

**Comment by Cipa** [comment]
backend - the code doesn't support the 'noconflict' mode and I am not sure it should. If someone is using other libraries, they should be the ones running their code in 'noconflict' mode.

frontend - we might have to keep this setting for QM to work but I think Qm was ignoring the setting anyway. Maybe we can open a new issue: QM noconflict mode not working.

**Comment by TimGS** [comment]
backend - OK, that seems reasonable - and now I remember, the noconflict setting is not used in the backend anyway.

frontend - Yes. Any frontend Extras need to use jQuery(), not $().

To clarify - the noconflict config setting is only actually used when including jquery via the API ($modx->regClientJquery()). If set to yes, the jQuery.noconflict() statement is added to the <head>. It's a frontend feature only.

**Comment by Cipa** [comment]
Closing as it will be done in #216
