### ISSUE TITLE
Develop: Res Manager installed next to Resource Manager

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#226]
But this may be the correct way.

**Comment by Cipa** [comment]
When I upgraded my local setup Res Manager was installed next to Resource Manager. So now I have Res Manager and Resource manager.
I don't think this is bug. Maybe I did not ran an upgrade in a long time, and since then Resource Manager was changed to Res Manager and the installer did not know how to overwrite the existing module.

**Comment by TimGS** [comment]
I don't think I ever had it as Resource Manager. Maybe install your local copy afresh - it may be something just left over from your development.
