### ISSUE TITLE
Develop: when creating a new template the textarea is too big because of the padding

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#228]
Basically the frame can be scrolled horizontally. The textarea seems to to have a forced width of 100% + 8px padding on each side. Maybe a wrapper can fix the problem

**Comment by TimGS** [comment]
Temporary fix done of setting width to 90%.

A bigger issue is the plethora of inline styles in the manager. These would be better removed, possibly changed, and put in common/style.css so theme authors can override them.
