### ISSUE TITLE
New sample site

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#230]
Probably just using Wayfinder and List.

Ideally featuring examples of all placeholder types, including the new cross-references and output modifiers (see http://www.clippercms.com/forum/new-board/ )

**Comment by TimGS** [comment]
We could always just use the Download and About sections of clippercms.com ?!

**Comment by microcipcip** [comment]
What you mean? For the content or for the design?

**Comment by TimGS** [comment]
Either or both.
