### ISSUE TITLE
Remove mootools from ClipperModern

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#232]
There are some styles in style.css that are labelled for mootools. @Cipa - are the needed anymore?

Also the login html file includes mootools.

**Comment by Cipa** [comment]
No they can be removed. For example these sections can be removed

```
/* ppb:
* Style mootools tooltips
*/
```

```
/* ppb:
* Some styling for legacy mode fieldsets
*/
```

Not sure about the rest of the styles, I guess we have to check them individually

**Comment by TimGS** [comment]
Lines 55-99 of manager/media/style/ClipperModern/html/login.html need converting to jquery.

I think that as per @Cipa 's comment lines 1603 to 1653 of manager/media/style/ClipperModern/style.css can be removed.

Once that's done there is no mootools left in the manager, and we can remove the manager mootools directory!

**Comment by microcipcip** [comment]
About the login area, is it possible to implement this design (http://www.jertix.org/demo/clippercms/login/index.htm)?

**Comment by TimGS** [comment]
I don't see why not, but maybe best defer it till 1.3 now?

**Comment by microcipcip** [comment]
Ok.

**Comment by TimGS** [comment]
It could be part of a new manager theme?

**Comment by microcipcip** [comment]
I think it should be part of the default theme for ClipperCMS. The current theme is basically the one of MODX Evolution with a different logo.

**Comment by nick0** [comment]
Just wanted to say that clipper login concept at the above link looks awesome microcipcip, fantastic work!

**Comment by Cipa** [comment]
I removed mootools from the login page and now almost all the mootools references are coming from the sample site. https://github.com/Cipa/ClipperCMS/commit/deff5fa6946898c762daf0f5d5453f7b75e16550
I know Salvatore is working on this so when ready we'll test one more time for mootools.
setup.data.sql should also be updated with new content and all the mootools and modx references should be removed. I guess we'll do this once the sample site is ready.

ajaxSearch is also referencing mootools, the file we want to remove. See the default.config.file for AjaxSearch and more. Who is supposed to update this snippet? Maybe we should just move the file for now inside ajaxSearch and update the config files.

**Comment by TimGS** [comment]
coroico coroico@wangba.fr is maintaining ajaxsearch. It is now at https://github.com/ClipperCMS/AjaxSearch. I have made some changes (v 1.10.0) but I have always consulted coroico out of courtesy.

AjaxSearch does include mootools, but as far as I am aware, only as frontend code. If developers want to use mootools in the frontend of their sites, that's up to them - it's not for us to decide how they handle their own javascript. As such, I see no reason to propose removing mootools from AjaxSearch unless it becomes a burdensome maintenance overhead that no one including the original author is willing to take on.

Having said that, I do think encouraging people to use jQuery as opposed to other libraries makes sense. I just don't think we should seek to _impose_ that for frontend code.

Important note re: version numbers and package names. As per my forum posting a few weeks ago, MODx have complicated the situation by updating AjaxSearch independently of coroico and without consulting him, but without changing the snippet name or making this situation clear. As such there are now two snippets going by the name of AjaxSearch - coroico's and MODx's fork with the same name - when discussing AjaxSearch here or on the Clipper forums we should understand we are discussing the original snippet, not the MODx fork of the same name. Also be aware that they also haven't updated version numbers of AjaxSearch (or to the best of my knowledge of any other bundled snippets they have changed), which could further confuse matters for them, but hopefully not for us.

**Comment by Cipa** [comment]
Tim - can do a search for mootools.js and let me know if it's ok to remove it.
I'm not sure what happend yesterday but now I get different results when searching for mootools.js(the one in the core) and I think we are safe to remove it.

**Comment by TimGS** [comment]
On reflection, I think we should leave it in for 1.2 as AjaxSearch (by default) requires it for ajax search mode. Other third party snippets may also require it, and authors should have more warning that it will be removed.

AjaxSearch has three JS modes - jquery, mootools (use the manager mootools script) and mootools2 (use ajax search's slimmed down mootools file). The default is mootools.

We can have a think about how to approach this later, probably in consultation with coroico. We could just update AjaxSearch (with the author's agreement) to now use jquery by default. Another option is for DocumentParser to insert the parameter for the JS mode if it is not present, and set it to jquery i.e. AjaxSearch under Clipper would effectively default to jquery, but the mootools2 option would still exist.

It is more an issue for new sites as upgrades don't delete existing files unless the developer deletes all of manager/ manually.

**Comment by Cipa** [comment]
I'm fine with both solutions. Keeping the file is on the safer side,
hopefully this is all the third party snippets you are talking about
require.
