### ISSUE TITLE
Installer needs to remove Docmanager

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#239]
Add @legacy_names functionality for modules to Installer (etc).

**Comment by bossloper** [comment]
Just checking what you mean by 'remove'. Is the intention to unpublish the docmanager module that is being replaced? I think this is the usual practice for outdated modules and plugins when running an install.

**Comment by TimGS** [comment]
Yes. Resmanager renders Docmanager obsolete.

The installer has the capability to disable obsolete plugins, but not modules - hence my note.
