### ISSUE TITLE
Manager Manager update

### ISSUE THREAD

**Issue by fourroses666** [ClipperCMS/ClipperCMS#24]
When i check  /assets/plugins/managermanager I see version 0.3.9

ManagerManager 0.3.11-pl is available! :)

**Comment by TimGS** [comment]
Should have been already fixed last week https://github.com/ClipperCMS/ClipperCMS/commit/7e2add21dae5e203d78e04d72b33ac3f1ea658ea

Do a git pull and check the version again.

thanks,
-- Tim.

**Comment by fourroses666** [comment]
I think I was in the wrong branche (1.0.6 instead of Clipper 1.1)

Going to install a version right now for testing.
