### ISSUE TITLE
Variable name clash in evalSnippet

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#241]
Tried upgrade from 1.1 to 1.2 Beta on site using a snippet via runSnippet. Snippet failed because it has a parameter **&name**. This clashes with the **$name** variable in the document parser **evalSnippet()** function in document.parser.class.inc.php. The effect of the **EXTR_SKIP** parameter for extract() is that the snippet receives the snippet name as parameter instead of the value passed as &name. Suggest the function's variable be called something less likely to clash with user snippet parameters.

**Comment by TimGS** [comment]
Fixed and the equivalent issue for other variables also addressed.

Also done for evalPlugin()

The convention used is that all variables in these methods are prefixed $___
