### ISSUE TITLE
Cannot sort menu items via Resmanager. Clicking on a parent just edits/views that document.

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#243]
Either to fix so as to mimic Doc Manager, or make an extra site tree in the main frame to use instead.

**Comment by Cipa** [comment]
Weird, used to work for me(doesn't work anymore), any ideas how that functionality is built. I looked around but I am not sure how the click behaviour is modify in the tree.

Thx

**Comment by TimGS** [comment]
Looking at clipper-1.1.3, function treeAction in the tree frame has different actions depending on the state of variable ca.

I think docmanager hijacks the 'parent' option, which I think (but haven't checked) is what is also used by the core when changing the parent of a document being edited.
