### ISSUE TITLE
Datepicker icon & localisation

### ISSUE THREAD

**Issue by ghost** [ClipperCMS/ClipperCMS#253]
There is a icon on the right hand to datepicker fields. I think, it is a relict from mootools  datepicker.
Is a language localisation for the datepicker planned?

**Comment by Cipa** [comment]
1. I think you are referring to the remove date icon, the one with minus sign, right? That icon should be there to reset the date or remove the date completely.
2. As for localisation, I think we need to have a longer discussion. Are you referring to a way to enter dates in another format? The plan is to switch to html5 date fields and have the browser settings dictate the way dates look.

**Comment by TimGS** [comment]
re: 2. Agreed. HTML5 inputs of type="date" submit the date to the server as YYYY-MM-DD. Browsers IIRC are still quite inconsistent in how they display this, but it's reasonable to suspect that they will standardise on display either based on the locale settings as detected by the browser on the user's computer, or via some sort of CSS extension.

There is still a lot of misconception about HTML5 dates, especially in the designer-developer community. It should be emphasised that they will standardise the format of dates _sent to the server_. Server side scripts e.g. PHP will receive the dates in the format YYYY-MM-DD - always. This is good for programmer-developers, it makes life so much easier for those writing such scripts. This does not specify how the dates are _displayed_ . As long as browsers get their act together (and why shouldn't they?) dates will not necessarily be displayed as YYYY-MM-DD but will use something the user recognises as a valid date format. Chrome is the most advanced browser in this respect at the moment.

**Comment by ghost** [comment]
1. Yes, i meant the remove date icon. I'm sorry, but I had not properly understood the function of the icon. Maybe a title-tag would be appropriate.
2. I don't meant a localisation of the date itself - an output of the date in german format as 02.05.2013 would be nice to have - , but i meant the localisation of the date selector. (see image)

![bildschirmfoto 2013-05-02 um 11 37 34](https://f.cloud.github.com/assets/2494136/453253/d3ef6320-b30d-11e2-8aee-63dfb01db314.png)

**Comment by Cipa** [comment]
1. I enabled the default browser tooltip so you can see the icon title https://github.com/Cipa/ClipperCMS/commit/531dc0e9664b792af03630099b8972226741e03c. Further improvments are:
   - move the "No Date" text in the language files
   - globally enable the jquery ui tooltips or create a special type of tooltip for icons with actions(different from the ones explaining some fields like pagetitle)
2. I guess you want this setting to work based on what language was setup in the configuration section. For this to work I think we need to synchronize the values in the language dropdown with what jquery date picker has. http://jqueryui.com/datepicker/#localization
   But I'm not sure this is still necessary if we switch to an HTML5 date field.

**Comment by TimGS** [comment]
Regarding the posted date, I agree with Cipa. For the time being we will use the current date format - then later the HTML5 format.

Practically speaking, future server side code will accept either the current format or the HTML5 yyyy-mm-dd format.

**Comment by Cipa** [comment]
@TimGS - when do you expect to have the html5 integrated. If not soon we could try to implement the localization

maybe we should close this issue and start a new one.

**Comment by ghost** [comment]
It certainly will take some time until all browsers, including the market leaders such as Firefox or IE, can handle HTML5 date fields. I support the proposal of Cipa.

**Comment by TimGS** [comment]
In summary:
1. the icon has been, or will be made, more clear as to it's purpose.
2. the datepicker's language e.g. May vs Mai vs etc etc etc should now perhaps be an issue for 1.3+. I think this was the OP's original meaning of localisation.
3. the posted date fields currently submit in dd-mm-yyyy as per MODx. In future they will post yyyy-mm-dd as per HTML5. Server side code can be made to handle both if required (it may not be).
4. Regarding HTML5, we need to have the discussion elsewhere.

I will close this issue because multiple issues are getting confused together, and open another for (2).
