### ISSUE TITLE
Backup page

### ISSUE THREAD

**Issue by ghost** [ClipperCMS/ClipperCMS#254]
In manager backup page the sizes of all database tables are not displayed correctly.
![Bildschirmfoto 2013-04-10 um 12 46 28](https://f.cloud.github.com/assets/2494136/361662/3013525e-a1cc-11e2-856f-f8ba0e5f6f29.png)

**Comment by yama** [comment]
Maybe, InnoDB?

**Comment by ghost** [comment]
Yes.
