### ISSUE TITLE
Implement TV previews in core (was ShowImageTvs widget pest returns)

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#257]
Using Clipper 1.2 on a site with image TVs, I find I am plagued once more with spurious "Page has been changed, do you really want to leave"? messages when I try to open a different reource, not having changed anything in the current one.

I think this is due to a change in managermanager/widgets/showimagetvs/showimagetvs.php, where a lot of $j... variables have changed to just $...

**Comment by TimGS** [comment]
The $j => $ change shouldn't be a factor as the manager uses jQuery in non-noconflict mode (excuse the double negative!), but I'm happy to stand corrected if need be!

**Comment by bossloper** [comment]
I have always (even back to MODx 1.x) had issues with the showimagetvs widget causing the page change trigger to fire.

The 'checkImageTVupdates' function (around line 90) in showimagetvs.php seems to be the issue. It triggers a "change" at least once, the first time it gets the image.

My workaround is to add a couple of lines to the function that checks the status of documentDirty before and after the change trigger. There may be a more elegant way, but it seems to work. See code below:

```
        // Monitor the image TVs for changes
        checkImageTVupdates = function () {
                $j(".imageField").each( function() {
                    var $this = $j(this);
                    if ($this.val() != $this.data("lastvalue") ) {
                        OLDdocumentDirty=documentDirty; // uxello fix for edit trigger
                        $this.trigger("change").data("lastvalue", $this.val());
                        documentDirty=OLDdocumentDirty; // uxello fix for edit trigger
                    }                       
                });
        }
```

Edit: I believe it is a backend manager issue only as the frontend QuickManager+ clears documentDirty before a cancel which hides this bug.

**Comment by kp52** [comment]
There have been other solutions, including one that's been through the hands of the original author in the MODX bugtracker. The point here is that there's no $j in Clipper 1.2 (I tried installing the widget file from 1.1, producing errors about its non-existence). I don't know all that much about jQuery and conflict modes; I do know the continual spurious messages are a right pain.

**Comment by bossloper** [comment]
The plugin runs ok for me in 1.2beta (that uses $ instead of $j) and displays image previews as expected ... though with the issue of triggering a change even if no change is made. But to me that indicates the javascript is running as if $ vs $j was causing an issue then the jQuery script would surely not run and the documentDirty would not be triggered.

Guess my fix does not fully fix it as yes it prevents a documentDirty trigger, but will also prevent a real change for the image being registered, though I think I prefer it that way round until a full fix is integrated.

**Comment by TimGS** [comment]
Maybe it's time to just dump the widget and have image previews in the core?

Whilst we have theoretically frozen features for 1.2 now, I'm wondering just how profitable it is spending time fixing this, when we could just (and quite simply) have image previews standardised in the core, with a couple of settings in the config for height and width.

**Comment by bossloper** [comment]
I'm all for moving popular functionality to the core (server side). The less client side script the better in my opinion.

**Comment by TimGS** [comment]
I've implemented this in the core.

It's a bit crude (fixed width and height) as I'm wondering whether to have these width/height options globally in the config or whether to have them specified on a per TV basis. Thoughts please - and also on whether to defer this to 1.3, as width/height is a nice luxury, but not essential.

Using the MM widget will do nothing other than insert a warning entry into the System log, saying that it doesn't exist anymore.

**Comment by TimGS** [comment]
As per above, image previews are now in the core. They are fixed at a maximum of 300x100 (the old MM default), and I propose this is what we go with for 1.2.

For 1.3, I propose that this width and height be set for each template variable i.e. in the tmplvars table. So, for example, all instances of a product-image TV would have the same width and height, but this could be different from instances of category-image.

I suggest splitting the implementation over 1.2 and 1.3 because we are at beta stage, and shouldn't be adding new features without good reason. I think this however is a reasonable compromise given that it fixes a bug (as reported by the OP) for 1.2.

**Comment by kp52** [comment]
Tested in fresh install on Windows 7 Home Premium, PHP 5.4.11, A[ache 2.4. No thumbnail icons, due to invalid path created at start of \manager\media\image\resize.php. Substituted:

```
$image_path = $_SERVER['DOCUMENT_ROOT'] . '/' . $_GET['src'];
```

for

```
$image_path = preg_replace('/manager\/.*$/', '/', dirname(__FILE__)).$_GET['src'];
```

and it works, but only after resource has been saved first time. Updating filename manually does not update the preview image until resource is saved.

**Comment by TimGS** [comment]
The former will only work (I think - untested) if the web root of the server is the site root i.e. if your site root is localhost/devsite/, $_SERVER['DOCUMENT_ROOT'] will only return the path to localhost e.g. /var/www, not /var/www/devsite, so the '/devsite' part of the path would be missed out.

I'll scratch my head as to why the current line doesn't work on your install. Does dirname(**FILE**) on Windows return a path with forward or backward slashes?

I might need to instead use

``` php
$image_path = preg_replace('/manager\\'.DIRECTORY_SEPARATOR.'.*$/', '/', dirname(__FILE__)).$_GET['src'];
```

**Comment by kp52** [comment]
Backward. 
Windows XP and later will recognize forward or backward slashes as directory separators, including mixtures in the same path. So how about:

```
$image_path = realpath('../../../') . '/' . $_GET['src'];
```

which works for me.

**Comment by TimGS** [comment]
Ah - my regular expression will fail on backward slashes. Your suggestion seems a reasonable solution - implemented.

**Comment by TimGS** [comment]
I think this is fixed - closing - please reopen if I'm wrong!
