### ISSUE TITLE
Manager Interface Issues with IE10 (Clipper 1.2beta)

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#259]
Couple of layout issues with 1.2beta on IE10

1) The sessTokenInput is visible (just) above the menu tree.

2) There is no space above the top tabs (Site, Elements, Modules etc) for the Change Password, Help, Logout panel to slide above the tabs. All looks fine in Firefox.

![ie10](https://f.cloud.github.com/assets/1744687/413172/d9af547e-abe6-11e2-800b-d72186288965.png)

**Comment by microcipcip** [comment]
Ok, thank you! I will review the issue.

**Comment by microcipcip** [comment]
I am unable to replicate this issue.Well, I am basically unable to use the manager in any version of Internet Explorer. Does anyone have this issue? I have attached a screenshot, as you can see the menu is broken. If I look the code with Internet Explorer Developer tools, I am unable to see the css styles.

![ie](https://f.cloud.github.com/assets/585402/624526/9a6317c8-cf87-11e2-8be4-39601530bd4b.jpg)

**Comment by kp52** [comment]
Working normally for me here in IE9 (64-bit). The tree was a little slow to appear on first entry.

**Comment by bossloper** [comment]
Yes looks fine for me under latest dev code. I think it must have been a cached css file.
