### ISSUE TITLE
Ditto calls (cached and uncached) not being parsed after upgrading

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#26]
Note: [[UltimateParent]] and [[Wayfinder...]] on the same site works. Presumably this is related to DocumentParser::snippetMap.

**Comment by nick0** [comment]
I am not sure if this is what you are referring to Tim...

...but having to cache a ditto call on an uncached page for ditto pagination to work is annoying. it should just work cached or uncached on a cached (or if required an uncached) page.

**Comment by TimGS** [comment]
No, thats not the same issue. The above posted issue - only relevant for Clipper 1.1 is solved.

Can you verify that the Ditto pagination issue still exists on Clipper 1.1.develop, and if so post a new issue.

Thanks.

**Comment by nick0** [comment]
ok sure thing Tim, I will do some testing of clipper
