### ISSUE TITLE
ManagerManager - ReferenceError with undefined variable savedPanelId

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#262]
Affects upgrade from 1.1 -> 1.2 and seen when editing a resource.

**Comment by Cipa** [comment]
Do you have a test case?
Is this still the case with 1.1.3?

**Comment by TimGS** [comment]
v1.2 beta i.e. develop branch.

Seen on all pages on my own site.

**Comment by Cipa** [comment]
I can't reproduce this. Can you give me a test case?

What I did in my case is to create a new TAB via MM and save the document from that tab. What is your setup?

**Comment by Cipa** [comment]
Can you please test this
https://github.com/Cipa/ClipperCMS/commit/3dfb4168f0d3be6ef2478200bf9e02a69aca29e2

If it fixes your problem please integrate

**Comment by Cipa** [comment]
Actually I will only do this for MM not for the manager.js. Let's see if it fixes your problem. I reverted this
https://github.com/Cipa/ClipperCMS/commit/71f338eb749940f9b21439ca1ec87f09db43ce7f
