### ISSUE TITLE
MySQL server strict sql_mode is enabled!

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#267]
On a server I get this message when I try to install

Connection to host: passed - collations now available
MySQL server strict sql_mode is enabled!

It is not clear what type of message is this and what should be done about it.

Thanks

**Comment by TimGS** [comment]
Probably more an issue for the forum (under Support), but I'd read http://dev.mysql.com/doc/refman/5.0/en/server-sql-mode.html.

Not something I know much about, but reading the above I wouldn't expect this on a shared host (is it?)

**Comment by Cipa** [comment]
It's not shared hosting. It's a dedicated server running IIS6 I believe. Probably MySql was not properly configure at install and now I'm trying to locate my.cnf or my.ini. 

My comment was about not showing more details about why this is a error. 
If you ignore it and keep installing you will get an error at the end. I did not know this when I posted the issue so I guess this is not an issue anymore ????

**Comment by TimGS** [comment]
We could indeed make it more explicit, maybe link to dev.mysql.com, or even refuse to carry on the install after this error.

I don't know enough about it to be sure though. Perhaps just leave it. The message gives a pointer as to the issue, and I think most people with commercial sites running on a dedicated server would have a sys admin to look after it, who would probably know enough to track down and sort the issue.

**Comment by Cipa** [comment]
Any ideas why we have a check for strict mode? I don't see any issues on my win server that has strict mode on but it is possible that when some fields are longer than in db or dates are not valid an error is shown.

**Comment by TimGS** [comment]
I think unless we get more info on this it's best to leave it as is. The warning is there and people are free to look it up. I suspect it's not going to make any difference most of the time anyway - as long as core code validates data before inserting into the db all is fine.
