### ISSUE TITLE
Remove datepicker workaround for IE9/10 (1.2dev)

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#268]
For develop branch 1.2 beta:

As datepicker is now jQuery based then the fix in the manager/index.php for IE9/10 forcing to IE8 is no longer needed. Around line 70 can be deleted:

header("X-UA-Compatible: IE=8"); // Datepicker needs fixing

**Comment by TimGS** [comment]
I'm inclined to suggest that this gets deferred to 1.3.

Removing it may be fine for the datepicker, but risks introducing other problems elsewhere in the manager.

**Comment by bossloper** [comment]
Possibly, thought does it depend on on how long you are holding 1.2 in beta for testing? The longer this stays in place the more likely it is code/css might be crafted that depends on it.

**Comment by TimGS** [comment]
This is to be confirmed, but sometime around the end of this month.

**Comment by TimGS** [comment]
PS. Speaking of which, feedback via the forum is always welcome. It's good to know what does work on 1.2, as well as what doesn't!

**Comment by TimGS** [comment]
@Cipa - do you see any problems here? I think the IE9/10 workaround was for the old datepicker? Can we remove it?

**Comment by TimGS** [comment]
@Cipa - bump!
