### ISSUE TITLE
changing a page from rich text to non rich text and vice versa - on click would be nice

### ISSUE THREAD

**Issue by nick0** [ClipperCMS/ClipperCMS#27]
When changing a resource's setting from rich text to non rich text, it would be nice for the content area wysiwyg to change on click - rather than having to save and close and then reopen the resource to access the non rich text content area.

And vice versa from non rich text to rich text.

**Comment by TimGS** [comment]
Are you able to submit a fix for the next version (1.2) ?

**Comment by nick0** [comment]
I wish!
I would love to Tim but alas I am not a programmer / coder - the mechanics of programming is like double dutch to me.
Sorry.

**Comment by Cipa** [comment]
This might be easier to do in version 4 of tinymce, 3 doesn't seem to have an api to enable/disable without refresh
