### ISSUE TITLE
Output Modifiers + List

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#271]
Output modifiers don't seem to be working with List/Ditto.
For example, try this: [+content;limit(200)+]

**Comment by TimGS** [comment]
They've only been implemented for content placeholders of the form [_..._].

List's placeholders are not handled by the parser, they are handled by List itself. For 1.2 you can use a snippet e.g. [!Limit? &len=`200` &value=`[+content+]`!].

For 1.3 we can implement output modifiers for List, and for [+...+] placeholders that are handled by the parser.
