### ISSUE TITLE
Language used in datepicker should reflect the manager (user's) language.

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#272]

**Comment by Cipa** [comment]
Hi all,

A quick fix to this is to add the following code to header.inc.php in the head portion. This might not work for all the languages as language codes differ slightly for some countries.

```
    <?php 

        if($modx_lang_attribute){
            echo '<script src="https://raw.github.com/jquery/jquery-ui/master/ui/i18n/jquery.ui.datepicker-'.$modx_lang_attribute.'.js"></script>';             
            echo '<script src="https://raw.github.com/trentrichardson/jQuery-Timepicker-Addon/master/i18n/jquery-ui-timepicker-'.$modx_lang_attribute.'.js"></script>';
        }

    ?>
```

What this does is to load the appropriate language files from github.

@TimGS - Let me know if you want this before the launch. I think that all we have to is to add the language files to assets/js/i18n folder and modify the code above to point to the appropriate files.

There is one problem for chinese, there are 2 files for the datepicker/timepicker combo
jquery-ui-timepicker-zh-CN.js
jquery-ui-timepicker-zh-TW.js

Clipper language has only 'zh', so I think for now we should rename jquery-ui-timepicker-zh-CN.js to jquery-ui-timepicker-zh.js and have it as default.

**Comment by TimGS** [comment]
I think at this point we should defer till 1.3.

re: zh-cn (simplified chinese) and zh-tw (traditional chinese). The chinese file in manager/includes/languages is simplified chinese. I don't think we should rename any jquery files - instead I think we should use jquery-ui-timepicker-zh-CN.js and this code should:

1) Use the file jquery-ui-timepicker-<lang code>.js if it exists.
or
2) Use the first file found matching jquery-ui-timepicker-<lang code>-*.js if any exist (probably easiest to use PHP's glob() function)
or if both the above fail,
3) Fallback to the english option.

-- Tim.

**Comment by Cipa** [comment]
How about changing the language code in the chinese language file?

**Comment by TimGS** [comment]
It would almost certainly result in problems elsewhere. At the moment code may reasonably assume that $modx_lang_attribute is a two letter alpha code as per ISO 639-1. I think this should stay the same otherwise we'll have a few bugs to find and fix.

**Comment by Cipa** [comment]
Should we add all the jquery datepicker language files?
https://github.com/jquery/jquery-ui/tree/master/ui/i18n

Or just the ones that we support?

Edit: Actually I don't think we can add all of them. For example for the chinese we use just 'zh' but jquery has 3 versions none of which is just 'zh-CN', 'zh-HK', 'zh-TW'. So for this to work we can only use one or hardcode the pick.

**Comment by TimGS** [comment]
Just the ones we support - unless that's most of them anyway, in which case might as well add the lot to make updates easier.

re: zh. Grab the simplified chinese file and use that as 'zh'.

**Comment by Cipa** [comment]
Have a look at https://github.com/Cipa/ClipperCMS/commit/fe5d29c5dac15a26e517e4933612c25a998bf0fb and let me know if this works for you. If it's ok I will submit a pull request

**Comment by TimGS** [comment]
Almost, and most of the time!
1. The glob() calls would be better if instead of finishing '_' they finished '_.js'. Some text editors append '~' or similar to the end of backup files - and this change would avoid them being read in error.
2. More of an issue is that the jquery language files are UTF-8 only. I'd suggest only including them if $modx_manager_charset is 'UTF-8'. Even just using ISO-8859-1 as the site charset mucks up some files e.g fr.

**Comment by TimGS** [comment]
I have cherry picked fe5d29c5dac15a26e517e4933612c25a998bf0fb and implemented the suggested tweaks.

At some point we may have to address what happens when the character set is not UTF-8. In the meantime the fallback of English will have to do.
