### ISSUE TITLE
Fix Tabs style

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#273]
Tabs style doesn't show up until jQuery is loaded (so during the loading of the resource), this is probably because jQuery UI apply some classes. We should fix this in the CSS so that tabs are visible even if jQuery UI has not loaded yet.

**Comment by TimGS** [comment]
This is probably something for common/style.css.

**Comment by Cipa** [comment]
This probably only happens the first time when you load the manager or after you cleared the cache.
I'm might be wrong but I don't think there is much we can do because jquery ui almost completly modifies the html. 

Can you confirm that this happens every time?

**Comment by microcipcip** [comment]
Yes, it happens everytime. You can see the issue online (not always, but almost), probably in localhost it loads too fast to be seen.

**Comment by TimGS** [comment]
Cipa is right about the HTML - and I'm also not sure what we can do about it. Targetting the generated HTML will only work until the jQuery folk change what HTML is generated.

Can you check in Firebug and other developer tools on other browsers whether the issue is the _loading_ of the jQuery (or any other) file, or whether it is just slow execution.

I've not noticed an issue myself but I have been using my local machine. I am however about to deploy 1.2 on a production site - probably on Monday - and will report back.

**Comment by Cipa** [comment]
I talked to Salvatore about this in private and so far I think that there
is a delay before manager.js is executed. Might be the
javascript embedded into the html of that page. We'll have to do some tests
and see when manager.js code is executed and what exactly delays that
execution.

**Comment by Cipa** [comment]
After some more testing it seems like the best solution is to apply some default styles/classes to the tabs, unless someone else thinks it could be a delay in execution.

I tested using https://developer.mozilla.org/en-US/docs/Web/API/console.time and I could not find any major delays. I could be doing it wrong.

**Comment by TimGS** [comment]
I've checked on a site running 1.2beta on a shared host - I see a delay on the first manager page load for the main tabs i.e. the topmost frame. I don't see any delay afterwards on any further page loads. Checked in Opera and IE9.

Either I misunderstand the issue (?), or - as I see it - there is nothing to fix!

**Comment by microcipcip** [comment]
I see the issue even after first loading (you can try on ClipperCMS demo website, it is random, I use Win7 64bit with Firefox). I didn't have time yet to fix this, as I was having some issues with the demo website, but will try to fix this at the beginning of next week.

**Comment by microcipcip** [comment]
Can you test this fix? On /manager/media/style/common/style.css add the following:

```
/**
 * Tabs
 */ 

.js-tabs {
    position:relative;
    padding:.2em;
    border:1px solid #aaa;
    background:#fff url(images/ui-bg_flat_75_ffffff_40x100.png) 50% 50% repeat-x;
    color:#222;
    -webkit-border-radius:4px;
       -moz-border-radius:4px;
            border-radius:4px;      
    }
.js-tabs > ul {
    margin:0;
    padding:.2em .2em 0;
    border:1px solid #aaa;
    background:#ccc url(images/ui-bg_highlight-soft_75_cccccc_1x100.png) 50% 50% repeat-x;
    color:#222;
    font-weight:bold;   
    -webkit-border-radius:4px;
       -moz-border-radius:4px;
            border-radius:4px;  
    }   
.js-tabs > ul:before, .js-tabs > ul:after { content: " "; display: table; }
.js-tabs > ul:after { clear: both; }
.js-tabs > ul > li {
    white-space:nowrap; 
    list-style:none;
    float:left;
    position:relative;
    top:0;
    margin: 1px .2em -1px 0;
    padding: 0 0 1px;
    border: 1px solid #AAAAAA;  
    border-bottom:0;    
    background: #FFF;
    color: #212121;
    font-weight: normal;
    -webkit-border-top-right-radius:4px;
        -moz-border-radius-topright:4px;
            border-top-right-radius:4px;    
    -webkit-border-top-left-radius:4px; 
        -moz-border-radius-topleft:4px;
            border-top-left-radius:4px;
    }
.js-tabs > ul > li > a {
    float:left;
    padding:.4em 1em;
    text-decoration:none;
    color:#212121;
    }
.js-tabs > div {
    padding:1em 1.4em;
    }
```

**Comment by TimGS** [comment]
Added. Feel free to close the issue if this is now fixed.

**Comment by microcipcip** [comment]
Does anyone found any issue with this fix? I have tried to delete assets/js/ folder and I see the tabs all right in all major browsers. Should I close it?

**Comment by TimGS** [comment]
Assuming you've checked the latest version of develop, and you are happy with it, close this one.

**Comment by Cipa** [comment]
Not sure if related but I think the 2 tabs Access Permission and Categories should not be visible OR why are they empty? Can you test on your setup?

![screen shot 2013-06-15 at 9 46 12 am](https://f.cloud.github.com/assets/293377/658162/12b070f0-d5c2-11e2-89ea-c1e9bd0037c1.png)

**Comment by TimGS** [comment]
Is this the old sample site, new sample site, or something else? Which docid?

**Comment by microcipcip** [comment]
I have installed ClipperCMS two times. One with the Demo Website and one without.
1) With the demo website installed, I see 3 tabs: General, Settings, Access Permissions (with All Resource Groups (Public)/Site Admin Pages).
2) Without demo website installed, I see 3 tabs: General, Settings, Access Permissions (empty).

 ~~Was "Access Permissions" tab hidden when it was empty, before my fix was applyed?~~
Edit: I have tried with ClipperCMS Demo (which doesn't have this change) and I can see "Access Permissions" tab even if it is empty. Was it available in previous versions of ClipperCMS (1.1.3?)

**Comment by TimGS** [comment]
There is an omission - see line 549 of mutate_content.dynamic.php. There is a todo still to be done!

Regarding the todo, JS seems the best option at the moment to avoid introducing bugs, but in the longer term (1.3?) it should be done server side. Alternatively, and perhaps more simply, perhaps if no document groups exist, and hence this tab is irrelevant as per the default 'minimal' install, we could simply put a note to that effect under this tab e.g. "No document groups exist and hence all documents are public."

**Comment by microcipcip** [comment]
Not sure about introducing new text as we would have to translate it. Maybe would be easier to remove the tab altogether? I guess we would have to test MM plugin after that, to make sure it still works.

**Comment by TimGS** [comment]
Translations not a big deal - in the absence of a translation the English is used as a fallback, so only this file need be complete. There are many strings that only exist in English - most new features that appear in the manager or are edited via the manager need some text. Also many language files don't look to have ever been complete e.g. Hebrew.

@Cipa - can you sort the manager JS to hide the tab if it is empty? I think you just need to hide the tab 'link' if the tab 'body' is absent - I'm sure you are more familiar with this than I am however. We may well need an alternative solution longer term, but at this point in proceedings I think this is best for 1.2.

**Comment by Cipa** [comment]
Ok

**Comment by microcipcip** [comment]
I am closing this issue. I don't think that the permissions tab being visible is linked to this fix.
