### ISSUE TITLE
Quick Manager "cancel" button not working

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#274]
When I open Quick Manager, if I click the "Cancel" button next to "Save" button, it does nothing and I see this error in the firebug: "TypeError: parent.$.fn.colorbox is undefined".

**Comment by bossloper** [comment]
I get a similar error if I have the Configuration -> Site "Use jQuery.noConflict()" setting set to 'Yes'. 
Switching it to 'No' worked for me.

**Comment by TimGS** [comment]
Fixed.
