### ISSUE TITLE
1.1.3 - errors on local setup with mamp and php5.4.4

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#276]
```
[06-May-2013 21:34:11 UTC] PHP Deprecated:  mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead. in /Users/local/Sites/startup/assets/plugins/managermanager/functions/utilities.inc.php on line 145
```

```
[06-May-2013 21:34:19 UTC] PHP Warning:  Illegal string offset 'template' in /Users/local/Sites/startup/assets/plugins/managermanager/mm.inc.php on line 60
```

The first one can be resolved by changing that function to mysql_real_escape_string.

The second one is weird. I think it might have something to do with $content['template'] but I am not sure.

Any ideas what it might be?

Thanks

**Comment by TimGS** [comment]
Are you sure you have an up to date ManagerManager? My local clone of the repo has line 145 of assets/plugins/managermanager/functions/utilities.inc.php already converted to $modx->db->query().

Nothing in the core or default install should have mysql_\* calls anymore, except for:
1. manager/includes/extenders/dbapi.mysql.class.inc.php
2. AjaxSearch - which tests for the existence of $modx->db->getVersion() (present on Clipper 1.2) but falls back to mysql_get_server_info() in it's absence.

**Comment by Cipa** [comment]
In the corner it says 1.1.3 and \* I just downloaded the files*
_if you look at
https://github.com/ClipperCMS/ClipperCMS/blob/clipper-1.1.3/assets/plugins/managermanager/functions/utilities.inc.phpyou
can see the mysql__ function
*

**Comment by TimGS** [comment]
Sorry, yes of course, it is an error in 1.1.3. Fixed in 1.2. We could release a 1.1.4 fix if it's deemed serious enough to not wait for 1.2 to be released (provisionally the end of the month).

**Comment by Cipa** [comment]
Everything seems to work. They are just warning in the end. 
At least lets document the fix for second error. I see only one difference between develop and 1.1.3, some extra (). 

This should be the fix

```
$mm_current_page['template'] = isset($_POST['template']) ? $_POST['template'] : (isset($content['template']) ? $content['template'] : $default_template);
```

**Comment by TimGS** [comment]
OK. Am I right in thinking that develop works fine on the same server setup?

**Comment by Cipa** [comment]
I don't remember seeing these errors but if I will check one more time

**Comment by Cipa** [comment]
No errors, should we close this than?

**Comment by TimGS** [comment]
Closing...
