### ISSUE TITLE
TinyMCE Skin

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#277]
As for ClipperCMS 1.1.3, TinyMCE skin should default to "o2k7 Silver":

skin : "o2k7", 
skin_variant : "silver"

**Comment by TimGS** [comment]
Which files need changing?

**Comment by yama** [comment]
https://github.com/ClipperCMS/ClipperCMS/blob/develop/assets/plugins/tinymce/js/mce_init.js.inc#L6
Insert this line.

**Comment by TimGS** [comment]
Thanks.
