### ISSUE TITLE
1.2 Default Child Template dropdown misleading

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#279]
The Default Child Template dropdown in the Create/edit Template screen shows "(blank)" as the current setting (unless you choose something else), "Create resource here" when nothing has been set in the Create/edit Template dropdown actually follows the setting in Configuration.

It would be helpful if the dropdown showed what will result from the current config setting rather than "(blank)".

**Comment by microcipcip** [comment]
Good idea, this would be better. For example: Default Child Template: "Use system setting".
