### ISSUE TITLE
1.2: no ajax with ajaxsearch under PHP 5.4

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#280]
Simple test page with AjaxSearch call below hangs on "Loading" image using latest version of Clipper 1.2 under Win 7 Home Premium, PHP 5.4.11

```
[!AjaxSearch? 
&jscript=`jquery`
&jsJquery=`[(jquery_url)]`
!]
```

Firebug reports syntax error in line 24 of ajaxSearch-jquery.js

Similar problem if AjaxSearch is using Mootools, so it looks as if it's whatever calls the javascript that is causing it.

Same call works using 1.2 on Linux host with 5.3.23, or on my local setup using MODX 1.0.6 (with adjustment for jquery location).

**Comment by TimGS** [comment]
If using Mootools, where does Firebug indicate the error is?

**Comment by kp52** [comment]
ajaxSearch.js line 25 col 1
Firebug report shows empty parentheses with cranked arrow pointing just after.

**Comment by TimGS** [comment]
I suspect the ajax response via index-ajax.php is returning empty. Can you check this in Firebug?

**Comment by kp52** [comment]
Not sure what I'm looking for here, but Ihave established a difference between Firebug readouts for the failing Clipper 1.2 test page and one on a MODX 1.0.6 site running in the same environment (i.e. under PHP 5.4). The Console/All screen shows some JSON data and a response for the successful (1.0.6) page after submitting a search; the Clipper one has identical POST data, but no JSON and no Response. 
![ajax-ok-json](https://f.cloud.github.com/assets/184620/495051/8cd7e094-bbb3-11e2-9d66-c54800d4164f.jpg)
![ajax-fail-post](https://f.cloud.github.com/assets/184620/495052/9472245e-bbb3-11e2-9952-200af01bbd7c.jpg)

**Comment by TimGS** [comment]
I've tried with PHP 5.4.11 under linux - and the posts work fine here.

I think we may need you to look in your error logs in your Windows Apache install. Alternatively:

Quick test - If you substitute index-ajax.php in the site root with the version from MODx 1.0.6 does it start working?

Not so quick test - If you install AjaxSearch 1.10.0 (https://github.com/ClipperCMS/AjaxSearch) in MODx 1.0.6 does this work?

This may help narrow down if it is AjaxSearch 1.10.0 or index-ajax.php (which has been modified for security) at fault.

-- Tim.

**Comment by kp52** [comment]
index-ajax.php from MODX 1.0.6 worked. Further checks revealed the problem: different directory separators in the string comparison towards the end of Clipper's index-ajax.php. Replacing

```
$allowed_dirs = array('assets/snippets/ajaxSearch/');
```

with

```
$allowed_dirs = array('assets||snippets||ajaxSearch||');
$allowed_dirs = str_replace('||', DIRECTORY_SEPARATOR, $allowed_dirs);
```

fixed it. You may prefer a more elegant solution.
:) KP

**Comment by TimGS** [comment]
Done. I put the second line in the code further down - just to separate the first 'config' line from the logic. 

We may have to separate the first line from this file. If anyone changes it for any sites, then on upgrade it will be overwritten. On the other hand I'd be quite happy to deprecate use of this file anyway - it is inherently a potential security issue if allowed_dirs is changed by someone who doesn't appreciate the pitfalls.

-- Tim.
