### ISSUE TITLE
QuickManager Cancel - If TinyMCE field altered it gives late message

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#281]
Issue:
Firefox and IE
Edit a resource at the frontend using QuickManager
Make an alteration to a TinyMCE field
Click Cancel

Result:
QuickManager windows closes THEN a message pops up saying 'are you sure you want to leave this page'
This message is too late in the process and clicking 'No' has no effect.

Also if a change is made to a none-TinyMCE field then no warning is displayed if cancelling and changes are just lost.

I have a potential fix. For more detail and an attached php file see: http://tracker.modx.com/issues/9935

**Comment by TimGS** [comment]
@uxello - I have implemented your code with minor changes as required for Clipper's QM+ version clipper-1.6. Can you check it is as intended?

Thanks.

**Comment by bossloper** [comment]
Yes, that is working as expected.

One thing I have just noticed. The 'advanced' TinyMCE theme does not have any plugin listed, hence there is no 'autosave' plugin which is needed to check for edit changes. 

See line 104 ish of assets/plugins/tinymce/tinymce.functions.php

Not sure if the total lack of plugins for the 'advanced theme' is by design or not??
Most of the other themes look fine, though 'simple' does not have the 'autosave' plugin.

**Comment by bossloper** [comment]
Still in dev... Just found a parameter miss-match when calling QM from the plugin. The call in the plugin has 19 parameters:

$qm = new Qm($modx, $modx->config['jquery_noconflict'], $loadtb, $tbwidth, $tbheight, $hidefields, $hidetabs, $hidesections, $addbutton, $custombutton, $managerbutton, $logout, $autohide, $editbuttons, $editbclass, $newbuttons, $newbclass, $tvbuttons, $tvbclass);

but the function in qm.inc.php has 21 parameters:

```
function Qm(&$modx, $noconflictjq='', $loadtb='', $tbwidth='', $tbheight='', $hidefields='', $hidetabs='', $hidesections='', $addbutton='', $tpltype='', $tplid='', $custombutton='', $managerbutton='', $logout='', $autohide='', $editbuttons='', $editbclass='', $newbuttons='', $newbclass='', $tvbuttons='', $tvbclass='')
```

It looks like $tpltype, $tplid, have been removed from the call. Spotted it as the 'Show go to manager button' option is not working because it is not picking up the correct option from the plugin.

**Comment by TimGS** [comment]
re: autosave. Don't know. Maybe discuss this on the forums.

**Comment by TimGS** [comment]
re: tpltype, tplid. I've a feeling these may be obsolete. Anyone disagree?

**Comment by TimGS** [comment]
tpltype and tplid now removed.
