### ISSUE TITLE
When editing a resource, child resources are highlighted in the LH tree

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#284]
When editing a container resource, it is correctly highlighted in the left hand tree frame.

However all child resources are also highlighted.

**Comment by Cipa** [comment]
I might be missing something. When I click on a container, only the container gets the border. The children look exactly the same but without the border.

Can I get a screenshot of what you see or maybe a test case?

**Comment by TimGS** [comment]
Further clarification - it's _only_ when right clicking on a resource and then selecting edit from the context menu. Furthermore then clicking another resource does not unhighlighted the earlier resource(s).

Single left clicking is fine.

**Comment by kp52** [comment]
Same here

**Comment by Cipa** [comment]
fixed, merge please
