### ISSUE TITLE
Wayfinder class="last" added even if only one item exists

### ISSUE THREAD

**Issue by nick0** [ClipperCMS/ClipperCMS#29]
This is probably in the latest version of Wayfinder, but I would love to see class="last" added when only one item exists - so we don't need to "hack" the original php file. 

Its come in handy in a few projects for styling the menus.
eg
- link 1
- link 2
- Item 2.1  (class = last is useful here for css)
- link 3
- Item 3.1
- Item 3.2
- Item 3.3
  etc

I found this in the forums years ago - changing line 92 in wayfinder.inc.php fixes this.

Original:
if ($counter == ($numSubItems) && $numSubItems > 1) {

Changing to >= 1 fixes this
if ($counter == ($numSubItems) && $numSubItems >= 1) {

**Comment by TimGS** [comment]
Changing the behaviour of the 'last' class would break existing sites.

One viable possibility is to have an 'only' class for when one item exists.

**Comment by nick0** [comment]
Possibly but I don't see how it would break sites if last is used for the closing li item in longer lists. That's should be an easy css tweak regardless.

I read that this issue was fixed in beta releases of Wayfinder but they never made it into 2.0.1.

An only class is a good workaround.

**Comment by TimGS** [comment]
If existing CSS assumes that a one-item menu does not have the last class, it _may_ break.

**Comment by TimGS** [comment]
One possibility is to add a parameter e.g. &lastOnUnique, that defaults to zero for backwards compatability.

If &lastOnUnique is 1, then Wayfinder would set the 'last' class on one-item lists.

Note also that CSS :last-child exists, but javascript workarounds are required for IE7 and IE8.

**Comment by Cipa** [comment]
I honestly don't see why waste time on this. IE8 is down to 25% so we can safely assume that in 1 year everyone will use css selectors.

If you are required to support IE9 and below I'm sure you will have some JS in the code but I might be wrong

**Comment by TimGS** [comment]
@Cipa I'm inclined to agree, and I don't intend implementing this myself, though I suspect you are being a bit optimistic about IE8's decline and I don't think JS is always or even usually needed to fix IE <=8. 

If a community member wants to submit a patch, should we accept it? The only case against would be code bloat, but I don't honestly think this will have more than a negligible effect.

**Comment by Cipa** [comment]
I don't see why not accept a patch if it helps some users.

**Comment by TimGS** [comment]
Agreed. I'll close the issue as the core team are not going to implement this, but if someone else wants to submit a patch that is bug free and secure, we'll accept it.
