### ISSUE TITLE
Res Manager bulk update failure

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#290]
Attempted to use Res Manager to update the Published flag on a block of resources on the live Demo website. It came back with a failure message. Same happened when a single resource was submitted.
![res-man-publish-set](https://f.cloud.github.com/assets/184620/624943/2e8acf72-cf92-11e2-890a-5eb684d973d6.jpg)
![res-man-publish-err](https://f.cloud.github.com/assets/184620/624946/371652ec-cf92-11e2-82a9-f23b4ca383f6.jpg)

**Comment by kp52** [comment]
Still not working for the "Other Properties" tab. There is nothing in the "newvalue" POST parameter when you try to update a field.

**Comment by Cipa** [comment]
Can you send me a test case?
I tested Resource dates and Misc Res Settings and it works ok on my local
setup. I also attached what I see in the post
![screen shot 2013-06-10 at 7 17 57 am](https://f.cloud.github.com/assets/293377/631273/9139aa62-d1c2-11e2-8b4e-93f6423d347b.png)

**Comment by kp52** [comment]
Working now - seems to have been a browser cache issue. I installed a fresh copy of Clipper-develop, and Res Manager worked for this feature in Firefox, but local copy of demo site (with updated files form same source, upgrade install etc.) continued to fail in both Firefox and IE9. 
Site worked OK in Chrome, which had never seen it before. 
Firefox fought a bitter struggle, but gave in eventually after I explicitly loaded a modified manager style.css file. Similar problem with IE9 went away after going into "Developer Tools" and requesting look at the JS console.
These things are sent to try us.
:| KP
