### ISSUE TITLE
Create subfolder option inside "images" not intuitive.

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#292]
Maybe we can hide the default 'images' folder and allow the context menu to be shown when you right click anywhere within the left panel. 

Or add a small note above the "images" folder

**Comment by microcipcip** [comment]
I am not sure about removing the "images" folder, that could make it even more difficult to understand. I think that once that the user understand the way ClipperCMS tree menu works, it shouldn't be too difficult to understand how to create nested folders, as it works in the same way as ClipperCMS itself.

An alternative would be to add a help page with instructions or maybe a button to add root folders? Not sure about adding a note above "images" folder as that would clutter the design considering you'll probably have to read it only once, after that it would only get in the way.

**Comment by TimGS** [comment]
I'm also happy to leave as is - but alternatively this may be worth posting in the forum for ideas and suggestions.

The context menu needs to only appear when right clicking on a folder as it relates to that folder (or subfolder). It could be confusing if another menu appeared anywhere.

One possibility is a 'menu' icon immediately after the folder name - normal clicking then activates the context menu. Going somewhat OT, this may be worthwhile for the Clipper tree menu also - after all, right click is a problem on touchscreens.

**Comment by Cipa** [comment]
I'm personally fine with it as is but it took me 30 seconds to figure it out. Now that I know it's easier

**Comment by TimGS** [comment]
Help button added to kcfinder.
