### ISSUE TITLE
Opera tabs underlining issue (?)

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#294]
Opera 12.15 shows an issue with the underlining in the tabs when hovered over. See screenshot where only part of the link is underlined. 

![screenshot - 150613 - 06 05 31](https://f.cloud.github.com/assets/311052/657723/bb77f418-d579-11e2-9509-2553d9b633ab.png)

**Comment by microcipcip** [comment]
I can't see this issue. Tested with latest version of Opera and Win7 64bit.
![opera](https://f.cloud.github.com/assets/585402/658122/030b893c-d5bd-11e2-988e-f5f242154d31.jpg)

**Comment by TimGS** [comment]
OK. I suspect it's an odd bug with this version or build of Opera, and not something widespread. Closing...
