### ISSUE TITLE
Resolve issue of multiple jquery includes when jquery included via templating.

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#298]

**Comment by Cipa** [comment]
This should help: http://stackoverflow.com/questions/1566595/can-i-use-multiple-versions-of-jquery-on-the-same-page

How about doing the above for all the frontend plugins? We could try to detect from the plugin if jquery is setup in the template and if it is and the version is different use a noconflict code.

Or maybe it's simpler just to add a noconflict flag/checkbox in the settings.

**Comment by TimGS** [comment]
The issue I am intending to be solved is where jQuery is included in a template e.g.

<script src="[(jquery_url)]"></script>

and then via API calls from snippets or plugins. At the moment multiple API calls to regClientJquery() will not result in multiple includes as the first call flags up jQuery as being present. Unfortunately the templating is independent of this, so two includes could (and will) result. As far as I am aware this isn't actually a big deal in no conflict mode, but can be otherwise.

I'm not proposing to provide a system for including multiple jQuery versions. That's inefficient and prone to odd bugs that many developers will not be able to solve reliably - plus anyone who _is_ capable of dealing with this is unlikely to need any crutches to help them.

**Comment by Cipa** [comment]
Honestly I am not really sure about any of this but here's how I see it

I was thinking of having all the frontend plugins run in noConflict by default and make sure that all the official clipper plugins use the same version of jquery. But in some cases, some plugins might require a different version of jquery. So basically worst case scenario we end up with:
- Clipper plugin using the official jquery supported by Clipper(QM in this case)
- Custom plugin using a different version
- Template using another version
  (could be more versions if multiple custom plugins are used/installed via package manager)

What is the best solution in this case?
Usually the template js code will run in regular mode, so the other 2 should run in noConflict mode. The easiest would be to always run plugins in noconflict mode. If you know what you're doing we could offer a config option to disable noConflict but will the custom plugin have it.

This is just my thinking. maybe there's a better way

**Comment by TimGS** [comment]
Until 1.8 -> 1.9 I never had an issue with the 'wrong' jQuery version. This does imply that in general, the issue is so small that it is reasonable to expect developers to just run one version of jQuery, and update their code (or plugin code) if and when required. I wouldn't ever consider using multiple versions, that's inefficient and asking for odd problems - I'd always update the code.

In the above example, I'd update the custom plugin to use the jQuery API methods now in Clipper, and update the plugin's javascript if necessary (unlikely). That would involve time, but so be it - it takes time to develop robust websites. For non-techies it would probably involve money instead - but again, so be it - after all time = money! Then I'd submit the updated plugin to the forthcoming Clipper Extras repo! If it is a currently maintained plugin I would consult with the author first out of courtesy as he/she may wish to update it themselves.

Same again for site-specific code. Chances are though that if you make a point of not using deprecated functionality (a reasonable restriction) then it will rarely or never be an issue.

This is getting a little OT however - best continue this in the forum if required, it doesn't relate to the issue as I intended it to be.

**Comment by Cipa** [comment]
I like "forcing" one jquery :) but I worry about some older plugins eg sliders that might not work using the newer version. If this becomes an issue the template should be the one that needs to be updated.

**Comment by microcipcip** [comment]
I think that ClipperCMS plugins should run in no-conflict mode by default, in this way the website will work without problems.

**Comment by TimGS** [comment]
No conflict mode is now the default in the frontend.
