### ISSUE TITLE
jQuery bug

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#300]
I have found a rather odd bug in the demo website which may be related to ClipperCMS 1.2. 

In the "head" tag section of the "Home" page (and only here!), I see the following code:

```

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://www.clippercms.com/demo/assets/plugins/qm/css/colorbox.css" media="screen" />
    <script type="text/javascript" src="assets/js/jquery.colorbox-min.js"></script>
```

Nothing odd in this, if I wasn't logged out from the website! Is this a known bug? You can check the website online for this. I have tried to save again the home page and also to clear the cache, however it doesn't seem to change.

**Comment by TimGS** [comment]
If you clear the cache and then log out before the home page is requested it clears. The home page is the only cached page.

It appears that QM's scripts are cached with cached pages. I'll look into a fix.

**Comment by TimGS** [comment]
QM+ has been modified to use the API functions for registering javascript / css, which seemed reasonable at the time. Problem is that these scripts or css files are cached.

This is probably fine for snippets. Cached snippets have their CSS/JS cached. Uncached snippets are run after the cache page entry is loaded, and their CSS/JS files are added at this point. Everything is intuitive.

Plugins however are a bit different. Any plugins run before DocumentParser::outputContent() have JS/CSS cached, as in this case. Any CSS/JS assigned by plugins run earlier e.g. QM+ and OnWebPageInit, are overridden. Plugins run after DocumentParser::outputContent() is called do not have JS/CSS cached and work as expected - except that some are run too late to affect the JS/CSS e.g. plugins attached to OnWebPagePrerender.

The plugins that are run too late to ever have any effect are probably not something to worry about. Plugins run too early are a bit more of an issue though. I'll have a think about possible solutions.

**Comment by TimGS** [comment]
A short term fix - for QM+ only - would be to clear the cache on log in and log out.

The issue should perhaps be considered in more depth for plugins in general for 1.3. Backwards compatibility versus forward development needs considering.
