### ISSUE TITLE
QM shows the configuration page when a site is installed and the configuration was not saved at least once

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#304]
Can we disable Qm until the configuration is saved.
Additionally when this happens, the Cancel button doesn't seem to work in this instance. Maybe the cancel works only for a specific type of content.

**Comment by TimGS** [comment]
Not sure what to do with this one. Currently the manager forces a save here before it allows a user to do anything else (IIRC MODx had a similar arrangement, but it was easily bypassed).

Can a user not just save the config from the QM iframe?

**Comment by TimGS** [comment]
I don't think this is a big deal. Perhaps for 1.3 we could maybe make sure that saving the config via QM closes the window - it doesn't at the moment, but it's a minor isse and I don't think worth delaying release for.

**Comment by Cipa** [comment]
Agreed

**Comment by TimGS** [comment]
Bug, but one to live with at this stage in development.
