### ISSUE TITLE
Login button for manager position

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#305]
![screen shot 2013-06-20 at 7 35 02 am](https://f.cloud.github.com/assets/293377/680815/75a6c5e0-d99d-11e2-9d95-0ad048093dee.png)

**Comment by Cipa** [comment]
Also related - Where is the Forgot Password functionality?

**Comment by TimGS** [comment]
Slightly puzzled - it looks fine here, and FMP is present. Browser?

**Comment by kp52** [comment]
I have a Forgot Manager link on the login panel. But only when the plugin is enabled. When it's disabled, the bottom of the Login button is outside the dialog box frame (on Windows 7 Home Premium, FF 18).
Also note the (c) year reads 2012!
![loginpanel](https://f.cloud.github.com/assets/184620/680852/d56ba7ce-d99e-11e2-89cf-7901e9d919e4.jpg)

**Comment by Cipa** [comment]
I reinstalled and everything is fine when the Forgot Manager Login is enabled. When disabled the page looks like in the screenshot I sent

**Comment by microcipcip** [comment]
I didn't know that "Forgot password" could be hidden. Try this fix on manager/media/style/ClipperModern/login.css from line 33:

```
    .sectionBody {padding: 20px 20px 5px;display: block;background: #fff;}
    .sectionBody:before, .sectionBody:after { content: " ";display: table; }
    .sectionBody:after { clear: both; }
```

P.S. where is the configuration setting to enable captcha? I would like to test the login with captcha enabled.

**Comment by Cipa** [comment]
I opened another issue for captcha. I think this one can be closed when your code is merged from my pull request
