### ISSUE TITLE
MM chunks settings could be better

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#306]
Looks weird when the table is only 700px wide on wider screens. Maybe we should use 100%

Also is there a way to make the rich text shorter. In the sample attached the rich text is used for captions which are usually one liners. Can we control the height of the Rich Text area?

![screen shot 2013-06-20 at 7 53 42 am](https://f.cloud.github.com/assets/293377/680895/8ca12300-d9a0-11e2-9dd2-70f55fe8d578.png)

**Comment by TimGS** [comment]
re: thumbs: see https://github.com/ClipperCMS/ClipperCMS/issues/257, for 1.3
re: richtext height. Not sure offhand, without writing your own plugin. Something for 1.3+?

**Comment by TimGS** [comment]
Closing - thumb sizes should go under https://github.com/ClipperCMS/ClipperCMS/issues/257.

Richtext height can have it's own issue, preferably I think to go in the core, not MM - but that can be discussed there.

**Comment by Cipa** [comment]
I was refering to the width of the table of 700 that is configured in the manager manager chunk. You can see that there is a lot of white space to the right. The functionality is ok.

And related the RichTextarea height I think the simplest way(if possible) is to allow the user to enter the height when they select "Rich Text" in the dropdown. But this is another issue.

**Comment by TimGS** [comment]
OK - reopening for Salvatore's comments,

**Comment by TimGS** [comment]
Is this just an MM issue or a more general manager presentation issue?

**Comment by Cipa** [comment]
I think is just presentation. I don't really mind it the way it is but I would like the width to be consistent with the other tabs.

**Comment by microcipcip** [comment]
Hi, you are right, 100% is much better. Regarding TinyMCE, maybe I should have used a mini textarea instead? Is there a way to use a simplified version of TinyMCE?

**Comment by TimGS** [comment]
@microcipcip - IIRC, unfortunately the TinyMCE plugin has one 'global' config. You cannot apply a different set of buttons to different instances. This is an issue and perhaps should be addressed. Maybe create a new issue for it?

**Comment by microcipcip** [comment]
Ok, I will.
