### ISSUE TITLE
QM - clicking on the clipper logo in the QM bar will make QM disappear and not return

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#308]
...and I can't seem to get back the bar even if I logout and relogin.

PS: I don't use QM so maybe this is the right way

**Comment by kp52** [comment]
It sets a cookie:
![qmcookie](https://f.cloud.github.com/assets/184620/681844/31318cc4-d9bb-11e2-9465-e63431e1b2c8.jpg)

**Comment by bossloper** [comment]
I think it is a side effect of the demo site. In particular something in:

assets/templates/clipperdemo/css/foundation.css

If you comment it out in the head chunk then it works.

**Comment by bossloper** [comment]
Seems to be the same culprit as for messing up color box (#303)

Line 418 in the demo site foundation.css.
position: relative on the body tag. If this is removed then the QM bar stays visible even when 'minimised'.

**Comment by Cipa** [comment]
I think 303 was fix. See latest commits. Overflow is only applied if the height of the window > height of the body.

**Comment by microcipcip** [comment]
The fix for this issue is in plugins/qm/css/style.css, line 221, add these 3 declarations for content-box:

```
#qmEditorClosed
{
    -webkit-box-sizing: content-box;
       -moz-box-sizing: content-box;
               box-sizing: content-box;
    height: 26px;
    display: none;
    width: 108px !important;
    cursor: pointer !important;
}
```
