### ISSUE TITLE
Option Dependent TVs: show / hide some template variables depending on the value of another template variable

### ISSUE THREAD

**Issue by nick0** [ClipperCMS/ClipperCMS#31]
Say you have a slideshow on the home page:
- Each slide in the slideshow contains a banner image, some text and a link.
  (taken from 3 separate template variables on a particular template)
- Ditto is used to include slides in the slideshow, using a filter.
- To add a page to the slideshow, you need to click the "add to slideshow" checkbox.
- Rather than an end user seeing all 4 slideshow template variables for pages not being added to the slideshow, it would be awesome to just show the one "add to slideshow" checkbox variable by default.
- And then when the "add to slideshow" checkbox is checked, the 3 slideshow template variables (image, text, link) are revealed (eg using jquery show / hide).

Or say you want to have a photo gallery on some pages:
- To add a photo gallery to a page, you need to click the "add photo gallery" checkbox.
- Doing so reveals the photo gallery template variables 
  (1 multiTV with image, thumb and title variables and 2 the scripts tv for the head)

Its a bit neater than showing all variables by default in a template and may avoid confusion for non technical users.

I would love this feature.

**Comment by AgelxNash** [comment]
minChars parameter and so present in AjaxSearch http://rtfm.modx.com/display/ADDON/AjaxSearch

**Comment by nick0** [comment]
Thanks - you replied in the wrong post..

I know the &minChars call.

But try using it for &minChars=2 at the moment without hacking those 2 files, I have never been able to get it to work without editing those 2 files.

**Comment by TimGS** [comment]
New feature proposals should now be discussed at http://www.clippercms.com/forum/feature-requests/

I _personally_ think this would be better as an Extra as I would query how widespread its application would be.

However do bring this up on the forum at the above location and see what others say. In the meantime I will close the issue.

**Comment by nick0** [comment]
Ok thanks Tim. Posted in the forum
