### ISSUE TITLE
List boxes fixed height?

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#310]
Anyone see this issue (latest develop)?

For example, QM plugin -> Configuration tab.

All the list boxes seem to be fixed height as if they were dropdown boxes. Makes selection tricky. This is IE10, Chrome and Firefox. OK in Opera.

![listboxes](https://f.cloud.github.com/assets/1744687/681850/49e878ae-d9bb-11e2-9960-247bf3c79e71.jpg)

**Comment by Cipa** [comment]
Can you please test this
https://github.com/Cipa/ClipperCMS/commit/dbd7480403304ddbc0755bee28cc58bf467d2b16

To make the single selects work the same on webkit I had to apply a height to them but I forgot to exclude multiple selects. Also size seems to have a say in the way they are displayed so I excluded all the selects having multiple and size attached to them.

**Comment by bossloper** [comment]
Yes, a quick test, your fix seems to work. Though in Chrome there is a large gap after each list:
![gaps](https://f.cloud.github.com/assets/1744687/682092/3f85bf98-d9c0-11e2-8830-28f9a64c4a30.jpg)

**Comment by Cipa** [comment]
Looks like that is the default size in chrome. Maybe we can update the js generating those fields to apply a size="" attribute. Should we do this for 1.3?

**Comment by Cipa** [comment]
Here's the bug and a solution, I'm not sure it's worth implementing
http://productforums.google.com/forum/#!topic/chrome/z4rBqNT3174

**Comment by bossloper** [comment]
@Cipa, No, would not bother. It looks ok, and maybe Chrome will fix it one day!
While looking at my screenshot above, do you think it would be possible to widen (or maybe make a % width) the parameter list so the label text for each item does not wrap so much? Same on all browsers, not just Chrome.
