### ISSUE TITLE
Enable captcha setting is missing but the words setting is still present

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#313]
@Tim: I am not familiar with this. Can you have a look at it?

**Comment by kp52** [comment]
We abolished it (see forum http://www.clippercms.com/forum/index.php?topic=139.0 especially Reply#1!). 
The words are still needed to use Captcha elsewhere, e.g. with eForm or Jot. 
If you desperately wanted it on the login page, the enable/disable setting still exists in the database table, though note the forum thread says the feature is not working anyway.

**Comment by tim** [comment]
@Cipa I am not familiar with it either, sorry!

**Comment by TimGS** [comment]
Wrong Tim!
