### ISSUE TITLE
Make the RichText smaller in height by default

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#314]
The reasons for this
- there is a small arrow in the bottom left corner that can be used to increase the size of the rich textarea
- when an area is resized with the arrow the dimensions are saved/cached by TinyMCE(I think) so when you open another doc or re-edit the same doc, the box will have new size not the default one, even if you logout(it might be a cookie)

My recommandation is to use a value of 250(currently 400) in the setup of TinyMCE plugin.

Alternatively we could force a different height for the content area and make the rich TVs smaller either by a new config setting either by using a percentage.

**Comment by Cipa** [comment]
I tested the above and it seems to work.

This is the config of the TinyMce
![screen shot 2013-06-20 at 11 31 30 pm](https://f.cloud.github.com/assets/293377/685270/260863aa-da23-11e2-80c1-110f1b5c448a.png)

This is the code that changes the height of the content(mce_init.js.inc)

```
$(window).on('load', function () {
  $("#ta_ifr").height([+content_height+]);
});
```

One line of code needs to be added to tinymce.functions.php
`$ph['content_height'] = (!empty($params['content_height'])) ? $params['content_height'] : '400';`

And off course the install part needs updating as well.

PS: This could be added to 1.3 unless there is a different plan. Maybe there is a better way of doing this.

**Comment by TimGS** [comment]
Deferred to 1.3.

**Comment by TimGS** [comment]
Maybe discuss this on the forum?

**Comment by Cipa** [comment]
sure

**Comment by TimGS** [comment]
OK. No one is objecting. Can you submit a pull request on the develop branch?

If possible I'd prefer a height in ems, but if that's a pain, pixels if fine.

-- Tim.

**Comment by TimGS** [comment]
Tried this. It now seems quite small! Not every user is computer literate enough to enlarge the textbox.
