### ISSUE TITLE
jQuery missing (QuickManager blank field)

### ISSUE THREAD

**Issue by fourroses666** [ClipperCMS/ClipperCMS#32]
Just installed a demo with clipper 1.1 dev and noticed front-editor is blank  (#edit QuickManager)

**Comment by TimGS** [comment]
Do you mean QuickManager?

**Comment by TimGS** [comment]
If so, can you verify if
a) It is installed under Elements->Plugins
b) Is it enabled
c) Are the other plugins installed e.g. ManagerManager should be there as version 0.3.11 and enabled.

**Comment by fourroses666** [comment]
Yes, QuickManager I mean.

When I want to edit the page there comes a popup, but its blank.
The blank page (iframe) URL: http://domain.nl/manager/index.php?a=27&id=1&quickmanager=1

Quick Manager+ 1.5.5 is installed under Plugins and active
ManagerManager 0.3.11 is installed and active

(if u want to take a visual look i can give you login)

**Comment by TimGS** [comment]
It's a jQuery issue, compounded by ManagerManager 0.3.11 defaulting to jQuery 1.7.1 but not supplying that file.

One solution is to standardise both plugins (and any others) with the jQuery file being assets/js/jquery.min.js (no version number). This does have pitfalls, but as long as we provide both plugins with the ability to override this then I think it is the lesser of all evils.

-- Tim.

**Comment by fourroses666** [comment]
I dunno exactly what u mean by "not supplying".
If it's being loaded 2x and conflicting or missing.

Standardising sound oké with me.

**Comment by TimGS** [comment]
ManagerManager (by default) expects jquery 1.7.1 in assets/js, but it isn't there.

**Comment by fourroses666** [comment]
ah ok, i dunno whats the best way to solve this. Should work after clean install.

**Comment by TimGS** [comment]
I'll make a common jquery file for ManagerManager and QuickManager.

You may well find that putting jQuery 1.7.1 in assets/js is a workaround.

**Comment by fourroses666** [comment]
Just to pinpoint something i wrote on a other pull.

WebLoginPE using the assets/js/jQuery 1.7.1.js or was planning to do so? 
<em>elegant mind issue 84 ?!</em>

**Comment by TimGS** [comment]
Indeed!

I think we need a $modx->loadJquery() method in the API. If a script needs jQuery it calls this. Multiple calls by multiple scripts have the same effect as one call, and the danger of loading multiple jquery versions is removed.

**Comment by fourroses666** [comment]
That will be a nice solution!

**Comment by TimGS** [comment]
The following have been added to the API:

$modx->regClientJquery()
$modx->regClientJqueryPlugin($plugin_name, $plugin_file, $plugin_version = 0, $use_plugin_dir = true)

Testing required!

**Comment by fourroses666** [comment]
sorry i have a fever

**Comment by bossloper** [comment]
Just been testing this out and looks good. 

Though if logged in as a manager and using QM+ then it still has two calls in the header. 

Looks like the QM+ call uses getJqueryTag which is not checking against regClientJquery ?

**Comment by TimGS** [comment]
@uxello Can you post the <head> source? Can you also post the QM plugin configuration string? Thanks.

I have just committed an update, but I suspect it doesn't relate to this bug

**Comment by bossloper** [comment]
I added a very simple snippet to the resource content of my test page to
ensure only included once:

<?php
$modx->regClientJquery();
$modx->regClientJquery();
$modx->regClientJquery();
?>

The QM plugin configuration string. This was a clean install and I left all
as default, though there is an odd 'undefined' at the start:

&1=undefined;; &loadmanagerjq=Load jQuery in manager;list;true,false;false
&loadfrontendjq=Load jQuery in front-end;list;true,false;true &loadtb=Load
modal box in front-end;list;true,false;true &tbwidth=Modal box window
width;text;80% &tbheight=Modal box window height;text;90% &hidefields=Hide
document fields from front-end editors;text;parent &hidetabs=Hide document
tabs from front-end editors;text; &hidesections=Hide document sections from
front-end editors;text; &addbutton=Show add document here
button;list;true,false;true &tpltype=New document template
type;list;parent,id,selected;parent &tplid=New document template id;int;3
&custombutton=Custom buttons;textarea; &managerbutton=Show go to manager
button;list;true,false;true &logout=Logout
to;list;manager,front-end;manager &disabled=Plugin disabled on
documents;text; &autohide=Autohide toolbar;list;true,false;false
&editbuttons=Inline edit buttons;list;true,false;false &editbclass=Edit
button CSS class;text;qm-edit &newbuttons=Inline new resource
buttons;list;true,false;false &newbclass=New resource button CSS
class;text;qm-new &tvbuttons=Inline template variable
buttons;list;true,false;false &tvbclass=Template variable button CSS
class;text;qm-tv

I will do another clean install at some point soon for further testing.

Richard

**Comment by TimGS** [comment]
I have checked on a clean install and all appears fine. Please repost if this issue appears again.

I have also fixed the &1=undefined issue.

thanks,
Tim.
