### ISSUE TITLE
Unable to delete a template

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#320]
I was trying to delete a template and I was unable to do it.
This are the actions that I've performed:
- Try to delete the template (it gave me the error that the template was in use).
- Open "Res Manager" and changed the template for some resources using the tab "Change Template".
- Went back and tryed to delete the template, but it didn't work. See below the errors from Firebug.
- Logging out and logging in again resolved the issue. I don't know exactly what caused it.

```
ReferenceError: $$ is not defined
[Break On This Error]   

$$('.tab-row .tab').addEvents({

index....15&a=16 (line 422)
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindow.confirm]
[Break On This Error]   

if(confirm("Are you sure you want to delete this Template?")==true) {

index....15&a=16 (line 134)
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindow.confirm]
[Break On This Error]   

if(confirm("Are you sure you want to delete this Template?")==true) {

index....15&a=16 (line 134)
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindow.confirm]
[Break On This Error]   

if(confirm("Are you sure you want to delete this Template?")==true) {

index....15&a=16 (line 134)
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindow.confirm]
[Break On This Error]   

if(confirm("Are you sure you want to delete this Template?")==true) {

index....15&a=16 (line 134)
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindow.confirm]
[Break On This Error]   

if(confirm("Are you sure you want to delete this Template?")==true) {

index....15&a=16 (line 134)
ReferenceError: $$ is not defined
[Break On This Error]   

$$('.tab-row .tab').addEvents({

index....15&a=16 (line 422)
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindow.confirm]
[Break On This Error]   

if(confirm("Are you sure you want to delete this Template?")==true) {
```

**Comment by Cipa** [comment]
I can't reproduce your steps but maybe I'm doing it wrong. Here are my steps
I tried to delete the Home template from the sample.
I got the message that I can't
Went to Res Manager and changed the template of the home page to Minimal
Template
Deleted Home page template with o issues

All went as expected. Can we get more details on this?

I also did a search for ".tab-row .tab' and nothing came out. Any other
ideas or details on this? Can you reproduce it one more time?

PS: I did find 2 console logs that I removed from resmanager.js. A patch
will be released as soon as we figure this out.

Edit:
Also could not find '$$' anywhere in Res Manager.

**Comment by microcipcip** [comment]
I will try tomorrow again and will let you know if I can reproduce the error again.

**Comment by TimGS** [comment]
I think Cipa's pull request may have fixed this. If so, close this.

Thanks.

**Comment by microcipcip** [comment]
I am closing this issue as I am unable to reproduce it.
