### ISSUE TITLE
ManagerManager actions on content field

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#328]
MM's renameField doesn't work - it seems to generate jquery that works on a table, whereas the content field is in a div.

The same error may exist for other MM functions on the content field (not checked).

**Comment by Cipa** [comment]
this works for me
`mm_renameField('longtitle', 'longest');`

**Comment by TimGS** [comment]
Indeed, but not on the _content_ field.

`mm_renameField('content', 'wibble');`

**Comment by Cipa** [comment]
weird, I don't get an error but the line has no effect. The Content title is not changed

**Comment by TimGS** [comment]
There's no error _message_. It doesn't work though because the generated jquery is looking for it in a table, which the content field isn't, so does nothing.

**Comment by TimGS** [comment]
`// ----------- Rename field -------------- 
$("textarea[name=ta]").parents("td").prev("td").children("span.warning").empty().prepend("Operational Info");`

...is the generated jquery, which cannot have any effect because the 'td's are not there.

**Comment by Cipa** [comment]
Add this on(or after) line 32 on functions/fields.inc.php

```
case 'content':
                    $output .= '$("#content_header.sectionHeader").html("'.jsSafe($newlabel).'");';
                break;
```

I would submit a pull request but I have some more changes done to my setup and I need to clean it first.

Thanks

**Comment by Cipa** [comment]
I also get a js error when I click on MM plugin. I think it's because of the additional tab that MM adds to the manager. The tab that contains some information about the TVs. I have to check using an older setup

**Comment by Cipa** [comment]
ignore the above, I was looking at the wrong install :(

**Comment by TimGS** [comment]
OK. Just for clarification, the noconflict setting is frontend only.

**Comment by Cipa** [comment]
Got it :)

**Comment by TimGS** [comment]
Code changed as per above. It may be worth checking other MM functions also for this case.
