### ISSUE TITLE
ManagerManager - move content field

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#329]
Another issue with the content field: before the introduction of jQuery in the manager I could move the content field below a template variable in this way:
mm_moveFieldsToTab('tvPicture,content', 'general','');

Is this still working?

**Comment by Cipa** [comment]
If you open the sample site in the manager you will see tabs and fields in
them. So I suppose they are working.
I can see the Slideshow and the Sidebar tabs and all the fields in them.

Did you have a different experience?

**Comment by microcipcip** [comment]
I am talking about the "Content" field, the main field with TinyMCE in it, in the first tab. Are you able to place a template variable over that field?

**Comment by Cipa** [comment]
I can move the field but I think you can't order it like you want. It's
always at the end in the tab. Is this the problem?

**Comment by TimGS** [comment]
Is this still a bug?

**Comment by microcipcip** [comment]
Yes, but I don't think it is a major issue, we can close it for now.
