### ISSUE TITLE
Error when saving a new manager user

### ISSUE THREAD

**Issue by MPerrine** [ClipperCMS/ClipperCMS#33]
I get an error with sql syntax when adding a new manager user

I needed to change li 156 of manager/processors/save_user.processor.php in order I create a new manager user to 

`$sql = 'INSERT INTO '.$dbase.'.`'.$table_prefix.'manager_users` (username, hashtype, salt, password)`

instead of

`$sql = 'INSERT INTO '.$dbase.'`'.$table_prefix.'manager_users` (username, hashtype, salt, password)`

(note the dot juste after $dbase)

**Comment by TimGS** [comment]
Oddly enough I couldn't get an SQL error, but I completely agree that the SQL should be changed as you suggest. 

Fixed and commited to 1.1.develop.

thanks,
Tim.
