### ISSUE TITLE
PM: requires @version entry for all element categories

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#330]
Elements with no version number are skipped (line 494)

```
    if (isset($name) && $version) {
```

Only snippets, plugins and modules should require a version number.

**Comment by TimGS** [comment]
Deliberate  - this forces package authors to have a version number for everything. In future the Package Manager can use this information to automatically check for updates and have as much information to hand as possible - as such _everything_ should have a version number.
