### ISSUE TITLE
German Umlauts in kcFinder

### ISSUE THREAD

**Issue by ghost** [ClipperCMS/ClipperCMS#335]
As asked in forum (topic: Rename files if they include german Umlauts): 
Replacement of  german umlauts when files are uploaded in kcFinder:

In assets/manager/media/browser/kcfinder/config.php:
Line 66: array 'filenameChangeChars'
and
Line 70: array 'dirnameChangeChars'
please add:

"Ä" => "Ae", 
"Ö" => "Oe", 
"Ü" => "Ue", 
"ä" => "ae", 
"ö" => "oe", 
"ü" => "ue", 
"è" => "e", 
"é" => "e", 
"à" => "a", 
"ß" => "ss"

**Comment by TimGS** [comment]
Can you check that https://github.com/ClipperCMS/ClipperCMS/blob/637f421fe656fe0a7dd57e2f4ebe1c845319e1a9/manager/media/browser/kcfinder/config.php does the job?
thanks,
-- Tim.

**Comment by ghost** [comment]
Hi Tim

In array «dirnameChangeChars» (line153) the german umlauts must also be included. Otherwise a user may create a subdirectory with a name like «Zürich».

Michael

BIG – Büro für Informatik und Gestaltung GmbH
Gertrudstrasse 46
8003 Zürich
Tel. 044 461 55 66
Fax 044 461 55 67

http://www.big-it.ch
info@big-it.ch

Ich unterstützte die Entwicklung von ClipperCMS. http://clippercms.de

Am 16.07.2013 um 21:15 schrieb TimGS notifications@github.com:

**Comment by TimGS** [comment]
@michael-big I've now added this to the dirname characters. Can you test?
thanks,
-- Tim.

**Comment by ghost** [comment]
Hi Tim

Tested it on my local MAMP with Safari Browser. It is OK.

Regards

Michael

BIG – Büro für Informatik und Gestaltung GmbH
Gertrudstrasse 46
8003 Zürich
Tel. 044 461 55 66
Fax 044 461 55 67

http://www.big-it.ch
info@big-it.ch

Ich unterstützte die Entwicklung von ClipperCMS. http://clippercms.de

Am 17.07.2013 um 11:15 schrieb TimGS notifications@github.com:

**Comment by TimGS** [comment]
Thanks,
-- Tim.

## www.timspencerweb.co.uk

Better a bad day in the hills than a good day in the office.

## See the hills at www.islandlight.co.uk
