### ISSUE TITLE
Deleting template

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#337]
Deleteing a template just gets the 'Template deleted' message.

Should this then redirect to the Elements->Templates page?

**Comment by Cipa** [comment]
This can only be done with js. any ideas on what message you want to show if any?

**Comment by TimGS** [comment]
Can we redirect with PHP and show a message on the  Elements->Templates page?

**Comment by Cipa** [comment]
not easy
It kind of was like this before but the header and footer were hard coded
so basically you end up having multiple versions/locations.

Maybe a local include for the footer and header will work. I have to try it

**Comment by TimGS** [comment]
Alternatively maybe when a user initially clicks the delete button we have a JS confirm() box - if the user clicks 'OK' we just go to Elements->Templates with no message.

Does this sound practical?

**Comment by Cipa** [comment]
This will not work as there are some checks that we have to do in order to
safely delete the template. Or I'm not getting what you ask :)
