### ISSUE TITLE
Resmanager changing template pagination issue

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#343]
When there are more than 20 templates, resmanager paginates the 'Change Template' tab.

Two issues...

1) The pagination is not obvious. I puzzled for a while as to why all my templates were not appearing, even taking the time to look in the Resmanager code for bugs - only to eventually notice the 1,2 in the top right hand corner

2) The 1,2 links don't fully work as the tab setting is not remembered.

Can we just dump the pagination? I can't see anyone having so many templates that this is required.

**Comment by Cipa** [comment]
I will look into dropping the pagination if you want. The plan was to change the pagination to use the dataTable plugin and ajax when the new template is implemented.

**Comment by TimGS** [comment]
I think it's worth dropping the pagination if no one has any objections.

**Comment by Cipa** [comment]
It seems there is a bug with the remember tab func. for ResManager. I will will fix that one first then drop the pagintion

**Comment by Cipa** [comment]
The pagination is used(if I remeber correctly) in other sections of the ResManager(tv lists for example). I'm not sure it should be dropped from all and for that reason not sure it should be dropped from templates. It has to be fixed anyway. I will get back to you with more details when I have time

**Comment by TimGS** [comment]
I can't see TVs or anything else in Resmanager warranting pagination.

**Comment by Cipa** [comment]
Well, in some cases you will end up with 100 TVs or more and pagination
might be required
I will remove it and we can address the pagination issue later on properly
if it's the case

**Comment by TimGS** [comment]
I can't really see 100 TVs being likely (or a problem even if it does occur). Plus there is no pagination on the elements pages, and people have managed just fine.

What I do have is a site with c. 25 templates, and the regular need to reassign some of the templates from the second page during the current development of this site!

**Comment by TimGS** [comment]
On the site in question I've changed lines 26 and 44 to pass 0 for the pageSize parameter to the DataGrid class. Leaving things as they were was just driving me nuts on this site. At the very least the page size needs to be way bigger (100?) but I'd seriously like to see how many sites have more than 100 templates or TVs.

**Comment by Cipa** [comment]
I see 2 options:
1. change the pageSize to 1000
2. remove DataGrid from Res manager

on 1 we can setup a config value for resManager and improve the look of 1/2/3 links
on 2 we have to redo how the table is generated.

I would go with 1 as it's a lot simpler

**Comment by Cipa** [comment]
Here's what implemented on my local setup
![screen shot 2013-08-17 at 8 40 27 am](https://f.cloud.github.com/assets/293377/980999/3ec398d0-073a-11e3-814f-234eb910f945.png)

Let me know if this works for you. Note that the pages are bottom and top so it's hard to miss.

Not sure about 
2) The 1,2 links don't fully work as the tab setting is not remembered.
When do you get this issue? Can I get a test case

**Comment by TimGS** [comment]
I don't see any point in removing DataGrid - that would just produce more work for no gain (as I see it), and we should get this done ASAP - it's the only issue remaining to be done for 1.2.1. 

Setting pageSize to 1000 (or any number from 100 upwards) is fine by me. Note that setting pageSize to 0 removes paging (this is what I did on the site in question).

re: _"The 1,2 links don't fully work as the tab setting is not remembered.  When do you get this issue? Can I get a test case."_ I think we may be at cross-wires here - is this fixed on develop via https://github.com/Cipa/ClipperCMS/commit/8877c655f5eb90dc689c001d33a67d1179f199ec? If so I will cherry pick this commit into the clipper-1.2.x branch (for 1.2.1).

**Comment by Cipa** [comment]
About the 1,2 links - I have not done anything to fix this because I can't see what the problem is.
