### ISSUE TITLE
TinyMCE - Use modern skin

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#36]
What about configuring TinyMCE to use the modern skin o2k7, silver variant?

skin : "o2k7", 
skin_variant : "silver"

**Comment by TimGS** [comment]
I think the TinyMCE plugin needs updating at some point to use the latest TinyMCE. 

Shall we assign both related issues to 1.2?

**Comment by bossloper** [comment]
FYI, 

I've updated to TinyMCE 3.4.9 ok on some of my sites. 

But if I go to TinyMCE  3.5.x (which has had significant rework I believe) then it mostly works ok but causes issues with the styles and paragraph dropdown and iframe with Internet Explorer / Chrome.

See this post on ModX forum: http://forums.modx.com/thread/75609/tinymce-3-5b3-and-new-windows

**Comment by TimGS** [comment]
Thanks. That info looks like it will save us some time.

**Comment by TimGS** [comment]
TinyMCE updated to 3.4.9 and new skin selected.

**Comment by bossloper** [comment]
The issue with TinyMCE and styles/paragraph dropdown with IE9 and Chrome iFrame appears to have been fixed in the latest TinyMCE version 3.5.7

**Comment by bossloper** [comment]
... though having said that there are other issues when trying to format paragraphs. Maybe best to stay on 3.4.9 until more of the bugs are fixed!
