### ISSUE TITLE
We should use 1 language code

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#361]
Currently we use:
$modx->config['manager_language'] - english
and
$modx_lang_attribute - en

Shouldn't there be only one?

**Comment by TimGS** [comment]
We could deprecate the former but keep it for extras that need it. 

An added issue is that the former is used for filenames both in the core and in extras.

**Comment by Cipa** [comment]
We could duplicate the file, rename them and use an include. 
This way we have only one version to mantain

**Comment by TimGS** [comment]
Desirable enhancement, but unlikely to be implemented now.
