### ISSUE TITLE
[BUG] Link to hide config alert not work

### ISSUE THREAD

**Issue by alooze** [ClipperCMS/ClipperCMS#364]
If disable option "check HTTP REFERER" in site configuration we can see alert in main page. With this alert show link for hide this alert. It`s broken.

![download](https://f.cloud.github.com/assets/1949044/1064149/49ac1f58-1313-11e3-8e18-79d45d0b921b.jpeg)

**Comment by TimGS** [comment]
The link calls a JS function - hence assigning it to @Cipa.
