### ISSUE TITLE
synch supported encodings with what php supports

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#365]
Should we update the supported encodings to what php supports:
http://php.net/manual/en/mbstring.supported-encodings.php

**Comment by TimGS** [comment]
Do you mean for the config setting modx_charset?

**Comment by TimGS** [comment]
If so, the manager language files are converted using iconv - so anything in http://www.gnu.org/software/libiconv/ is supported. 

I've just pushed an edit to develop to improve the fallback behaviour if iconv fails to convert - the improvement covers character encodings that are unsupported by iconv.
