### ISSUE TITLE
« Fatal error: syntax error, unexpected T_VARIABLE »

### ISSUE THREAD

**Issue by 2IDs** [ClipperCMS/ClipperCMS#368]
Hi out there ...i get this error if i press in the navigation the "Recipes" or "Help" Button in the DEMO-INSTALLATION-FILES if i am on the previewsite ( Liveside )

« ClipperCMS Parse Error »
ClipperCMS encountered the following error while attempting to parse the requested resource:
« Fatal error: syntax error, unexpected T_VARIABLE »

PHP error debug
  Error:    syntax error, unexpected T_VARIABLE  
  Error type/ Nr.:  Parsing Error - 4  
  File:     /var/www/clients/client1/web5/web/demo/clipcms/assets/snippets/list/lang/german.inc.php  
  Line:     1    

Parser timing
  MySQL:    0.0006 s    (7 Requests)
  PHP:  0.0164 s  
  Total:    0.0170 s

**Comment by TimGS** [comment]
Are you running version 1.2.1?

**Comment by TimGS** [comment]
Does replacing assets/snippets/list/lang/german.inc.php with https://raw.github.com/ClipperCMS/ClipperCMS/7e6edc2b4fcd71d40c3c5010c9d2991f7ad15bcf/assets/snippets/list/lang/german.inc.php solve this?

**Comment by 2IDs** [comment]
YEAAH...GREAT This fixed it. Thank you very much!
Have a nice day an go on. With best wishes 2IDs media:design RON www.2IDs.de

2013/9/12 TimGS notifications@github.com

**Comment by TimGS** [comment]
Fixed in develop branch for v 1.3
