### ISSUE TITLE
Datepicker not displaying with IE9

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#37]
This seems only to be an IE9 issue. If clicking the Publish date or un-publish date fields for any page then the datepicker does not display, only a thin blue line.

I have a simple workaround. Change line 70 of the manager index.php from:

header("X-UA-Compatible: IE=edge;FF=3;OtherUA=4");

to

header("X-UA-Compatible: IE=IE8;FF=3;OtherUA=4");

...but it does not address whatever the root cause is!

Having said that, it may not be wise to let IE use the latest engine (IE=edge) in the X-UA-Compatibile string? After all the other browsers are restricted (FF=3, OtherUA=4).

**Comment by TimGS** [comment]
Workaround used as a temporary fix.

Mootools is likely to be dropped in favour of jQuery, so there is little point in us upgrading (which with mootools is not a straightforward process).

thanks,
Tim.

**Comment by bossloper** [comment]
Just upgraded to the latest development branch today and this fix is now not working. 
Not working for either ClipperCarbon or ClipperModern themes on IE9 or IE10.

UPDATE- Looks like it was my fault with the initial code I gave you. It was only working because of the OtherUA=4. Then when you cleaned that out it stopped working.

Correct syntax is:

header("X-UA-Compatible: IE=8"); // Datepicker needs fixing

That fully works for IE9, only partially works for IE10 though. The dropdown works in IE10 but when you try and change the month it crashes IE10!

**Comment by TimGS** [comment]
What do you mean by "it crashes" ?

**Comment by bossloper** [comment]
RE: 'Craches' - I get an 'Internet Explorer has stopped working' dialog box.
There is a 'Close program' button on the dialog and that is it, IE shuts down completely, no option to carry on.

**Comment by TimGS** [comment]
Do you get the same problems with MODx Evo 1.0.6 or 1.0.7?

**Comment by bossloper** [comment]
Yes exactly the same on Evo 1.0.6. So no drop-down at all unless I add header("X-UA-Compatible: IE=8");
Then if I change the month I get the same IE 'crash'. Can change the day ok within the current month.

**Comment by TimGS** [comment]
We are planning to completely update the javascript in the manager to use jquery for 1.2. The current datepicker will become obsolete and be replaced by the jquery UI datepicker, and possibly a native HTML5 picker on relevant browsers.

We haven't had any more reports of the above datepicker bug in IE10, and there are no mentions on the modx forums that I can find. I'd check myself, but I haven't got Windows 8, and my attempt to install the IE10 preview on Windows 7 is being less than successful. Unfortunately MS are not providing (yet) any IE10 VPC images.

I suspect a rogue build of IE10. If it was a javascript bug, or even a typical cross-browser bug on the part of Microsoft, it would be unlikely to cause IE10 to crash completely.

As such, on balance I am labelling this 'won't fix' for 1.1. Regarding 1.2, the datepicker will be entirely new!

Hope this is OK. If we get information of people reproducing this bug in current builds of IE10, we will reconsider the issue.

thanks,
Tim.

**Comment by bossloper** [comment]
I found out when it causes the crash. If you run IE10 in the new 'Protected mode' (under the security tab) then this is when IE10 crashes.

**Comment by bossloper** [comment]
But from a previous post the fix for IE9/10 that you added will not work unless you correct the header line to:

header("X-UA-Compatible: IE=8"); // Datepicker needs fixing

**Comment by TimGS** [comment]
Corrected. Thanks.
