### ISSUE TITLE
save user processor

### ISSUE THREAD

**Issue by AgelxNash** [ClipperCMS/ClipperCMS#374]
trim() expects parameter 1 to be string, array given in manager\processors\save_user.processor.php on line 530

**Comment by AgelxNash** [comment]
Look: https://github.com/AgelxNash/ClipperCMS/commit/30fc2c71c149d99bbdbf0eb353e8ed0e7fcc549b

**Comment by TimGS** [comment]
Why do you implode array values? _If_ they are not used I'd rather just dump them.

**Comment by AgelxNash** [comment]
It is necessary for setting allowed_days

**Comment by TimGS** [comment]
I see - is that a new setting in MODx >= 1.0.9 ?

**Comment by AgelxNash** [comment]
This option was always there

**Comment by TimGS** [comment]
OK - I take it there was a bug previously with allowed_days and https://github.com/AgelxNash/ClipperCMS/commit/30fc2c71c149d99bbdbf0eb353e8ed0e7fcc549b fixes it? If so I will cherry-pick that commit into Clipper's develop branch.

**Comment by AgelxNash** [comment]
Yes

**Comment by TimGS** [comment]
Fixed via pull request #373 from @AgelxNash
