### ISSUE TITLE
Custom cache class

### ISSUE THREAD

**Issue by AgelxNash** [ClipperCMS/ClipperCMS#376]
Now the class name of the cache is defined in DocumentParser class. It would be great to be able to replace this class without losing the ability to update CMS.

I see such a realization: place the name of the class/class path in config.inc.php. From the functions of class DocumentParser submitted in the names of which are predetermined cache files (even if the new method in the class itself returns the names of files/data).

What do you think about this?

_Sorry for my google translate:-)_

**Comment by TimGS** [comment]
Yes - this is something that has come up before. It's something we could possibly do, though it should be discussed in the features area of the forum. http://www.clippercms.com/forum/feature-requests/

I'm closing the issue, but do start a forum thread.

-- Tim.
