### ISSUE TITLE
PM: descriptions run off screen

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#380]
Descriptions shown in Package Manager for fetched packages need word-wrap for the text wrapped in &lt;pre&gt; tags, otherwise they can easily stretch off the screen in one long line.
e.g. <code> &lt;pre style="white-space: pre-wrap;"&gt;</code>

**Comment by TimGS** [comment]
https://github.com/ClipperCMS/ClipperCMS/commit/e35b094616dd122fa8d2394f0164c80ffaef1e4c should fix this.
