### ISSUE TITLE
Fix tmplvars.inc.php for MultiTV path issue

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#386]
=> https://github.com/dmi3yy/evolution/commit/44741837ac0eab6573c2d9ad3e29dc9d754978de

**Comment by TimGS** [comment]
I have cherry picked that commit into clipper-1.2.x

Can you test? Most importantly, check everything else still works with TVs after the change - that file is used a lot!

**Comment by microcipcip** [comment]
Ok, I will let you know. I have already made this change some time ago in my localhost website, and I didn't find any issue yet.
