### ISSUE TITLE
WebloginPE - Error always displaying on &loginFormTpl template

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#389]
When I open www.sitename.com/account.html?service=login, which use &loginFormTpl, I always see this error from the [+wlpe.message+] placeholder: "You have left some required form fields blank.", even though I haven't submit anything yet.

**Comment by TimGS** [comment]
If you can give me access to the offending site it would be useful.

**Comment by TimGS** [comment]
Completely unchecked but try https://raw.github.com/ClipperCMS/ClipperCMS/7b0cb9450ab074e6e19966998ce86bce1f725454/assets/snippets/webusers/webusers.snippet.php

**Comment by microcipcip** [comment]
I still see the issue

**Comment by TimGS** [comment]
Try
https://raw.github.com/ClipperCMS/ClipperCMS/81f3c3de42b6bf3fdd220b03b951513cc3bdd8b4/assets/snippets/webusers/webusers.snippet.php

**Comment by microcipcip** [comment]
This works!
