### ISSUE TITLE
some incorrect links in the documentation

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#393]
The 2 links in the screenshot are not correct.
http://www.clippercms.com/documentation/construction/tags-doc.html
![screen shot 2013-11-08 at 7 55 00 am](https://f.cloud.github.com/assets/293377/1500351/11c5fda6-4875-11e3-9dac-6d61d5094259.png)

**Comment by kp52** [comment]
Fixed; also Using Snippets link in next section.
