### ISSUE TITLE
Upgrade to TinyMCE 4.0?

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#395]
Do you think it would be worthwhile to upgrade TinyMCE?
TinyMCE 4.0 seems a complete rewrite, so maybe it is not a simple implementation.

http://www.tinymce.com/wiki.php/Tutorial:Migration_guide_from_3.x

**Comment by kp52** [comment]
Interesting note towards the end of the linked article: 
    >>TinyMCE produces HTML5 loose output as of 4.0. This means it can handle all new HTML5 elements and also allow the deprecated HTML4 attributes and elements.

**Comment by Cipa** [comment]
Is there something done already I could look at, seems like current version has some problems with webkit(Safari/Chrome) and in some cases it inserts spans with line-height and font-size and other styles.

**Comment by Jako** [comment]
Maybe a good start: https://github.com/yama/tinymce4-for-modx-evo

**Comment by yama** [comment]
Sorry, I forgot it. I begin it now.

**Comment by Cipa** [comment]
@yama - are you working on providing a pull request for Clipper?
If not I can try, maybe you can send me some instructions on how to integrate.
Thank you

**Comment by TimGS** [comment]
Probably won't upgrade beyond v3 now. Happy to take pull requests though if tested.
