### ISSUE TITLE
File Manager permissions

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#397]
If I go to "Security > Manager User" and I select a user, then I open the tab "User" and I deselect the checkbox for "Uploadable Image Types", "Uploadable Media Types", etc, when I try to upload an image or another media in the File Manager, I shouldn't be allowed to upload. Instead, it seems I can do that. I have tried this with ClipperCMS 1.2.0. Has this been fixed since then?

**Comment by TimGS** [comment]
No idea. Only one way to find out for sure!

**Comment by kp52** [comment]
Setting works for me with Clipper 1.2.6. Created test user, cleared those checkboxes and left input empty. User logged in, and was not allowed to upload a JPG file. User logged out. I set specific allowed file types (jpg, log), test user logged in and was able to upload JPG file, but not a TXT file. As usual, current permissions are only updated at login.

**Comment by microcipcip** [comment]
I guess the problem is with previous versions of ClipperCMS. I will upgrade now and see if this fix the issue.

**Comment by microcipcip** [comment]
I have updated ClipperCMS to 1.2.6, however I am still seeing the issue. I am able to upload images although I don't have the permissions to do so.

**Comment by TimGS** [comment]
Is this a kcfinder bug or mcpuk bug or both?

**Comment by Cipa** [comment]
Unless I am missing something the user settings are not imported into kcfinder. There is no way to tell from the config settings that the user has or doesn't have access. I am looking into this at the moment but I am not sure what to look for or how to import user settings present in clpr_user_settings table.

I tried getUserSettings but I am not sure how that function works, shouldn't the settings be added to $modx->config?

**Comment by TimGS** [comment]
I think the clipper integration file incorrectly omits to call $modx->getUserSettings() which should indeed merge the user settings into $modx->config.

**Comment by Cipa** [comment]
I tried calling both and dumping the config but no new information was added to the config

**Comment by TimGS** [comment]
Did you check whether the logged in user had any settings that differed from the system settings?

**Comment by Cipa** [comment]
Actually I think the config is ok. Problem is I can't find a way to disable upload for some folders while allowing the upload for others.

Unless there is a way to tell kcfinder that you don't want to allow to upload images we have to detect the required type in the url (type=images) and compare it with what the user has setup

Still looking for a place where I can do this.

**Comment by Cipa** [comment]
I think I have a solution. 
But I was thinking, if upload is disabled should we allow any of these:
- delete
- copy
- move
- rename

Thoughts?

**Comment by Cipa** [comment]
Please test https://github.com/Cipa/ClipperCMS/commit/a487c8fcf20bbae7e4cd70313cd594010e006bb7

**Comment by TimGS** [comment]
re: delete etc. Probably not.

**Comment by Cipa** [comment]
The fix above allows delete copy etc, I can submit another pull request with the new changes

**Comment by TimGS** [comment]
I think there may have been some confusion between the file manager under 'Elements -> Manage Files' and kcfinder/mcpuk.

On the assumption (?) that it was kcfinder involved, this should now be fixed (please test!).
