### ISSUE TITLE
Clipper-Develop: login.processor.php blocks login on local/shared hosting

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#398]
Lines 119-122 of manager/processors/login.processor.php in Clipper-Develop cause an error when you try to log in on local hosting on your PC or on shared hosting.

```
"Your hostname doesn't point back to your IP!"
```

This logic used to be inactive unless the user was restricted to logging in from specific IP addresses, now it is applied to every login. I get the same error on MODX 1.0.5 when I enable IP restrictions for a user on shared hosting. Maybe it has never worked, and nobody ever tried restricting the logins.

I suggest this section of code be deleted. Actual checking of IP address, when enabled, happens in the next "case" statement. 

Line 91 (get host name into a variable) would probably become redundant, as well.

```
(91) $hostname = gethostbyaddr($_SERVER['REMOTE_ADDR']);

(119) case (($hostname != $_SERVER['REMOTE_ADDR']) && (gethostbyname($hostname) != $_SERVER['REMOTE_ADDR'])):{ // allowed ip
    $jsAlert = "Your hostname doesn't point back to your IP!";
    break;
}
```

**Comment by TimGS** [comment]
Fixed in https://github.com/ClipperCMS/ClipperCMS/commit/3c5c42b8a904ecaa47715aabe7dedc50aff47cdc
