### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#4]

**Comment by AgelxNash** [comment]
Why not integrate with the [plugin diff](https://github.com/AgelxNash/diffplugin4modx/blob/master/assets/plugins/diff/diff.plugin.inc.txt)?

**Comment by TimGS** [comment]
Can you set up a demo?

**Comment by AgelxNash** [comment]
http://diff.agelnash.ru/manager/
admin:123123

See the Version tab http://take.ms/0X9cKh

To adapt a ClipperCMS need a little refactoring function [ElementVer::render](https://github.com/AgelxNash/diffplugin4modx/blob/master/assets/plugins/diff/version.class.php#L402)

**Comment by TimGS** [comment]
Looks good, though I'd suggest it remain as a plugin, not part of the core.

For running on Clipper:
1. The jquery variable name should always be '$'. Changing the setting in the properties to be empty works fine if lines 405-407 of the main class file are commented out. Are these lines needed anyway?
2. Markup needs fixing for Clipper

I also found a more general bug in the ajax file - this file currently assumes that $_SERVER['DOCUMENT_ROOT'] is the site root. A possible fix is:

```
$rootdir = preg_replace('~/assets/plugins/diff$~', '', dirname(__FILE__));

if(isset($rootdir) && file_exists($rootdir.'/manager/includes/protect.inc.php')){
    require_once $rootdir.'/manager/includes/protect.inc.php'; 
    if (!$rt = @include_once $rootdir."/manager/includes/config.inc.php") {
        return;
    }
}else{
    return;
}
```

**Comment by AgelxNash** [comment]
I think such functionality is not needed in the kernel if it is ready to plug-in. Although you decide ...

1) Of course we can send line 405-407 in a comments
2) Yes, need to edit the plugin code JavaScript

P.S. Thank you for your bug-report

**Comment by TimGS** [comment]
OK - I will submit a pull request later on for (2) that should be compatible with both MODx and ClipperCMS.
