### ISSUE TITLE
russian UTF8 in tinymce and resmanager

### ISSUE THREAD

**Issue by rellai** [ClipperCMS/ClipperCMS#401]
invalid encoding  in tinymce and resmanager

Need to rename files
assets/plugins/tinymce/lang/russian-UTF8.inc.php
to
assets/plugins/tinymce/lang/russian.inc.php

and
assets/modules/resmanager/lang/russian-UTF8.inc.php
to
assets/modules/resmanager/lang/russian.inc.php

**Comment by TimGS** [comment]
Have you checked the develop branch?

**Comment by rellai** [comment]
I tested 1.2.6.Now all is well
