### ISSUE TITLE
Replace russian.inc.php

### ISSUE THREAD

**Issue by rellai** [ClipperCMS/ClipperCMS#402]
Please update /manager/includes/lang/russian.inc.php
http://pastebin.com/S5ZR5MQJ

**Comment by kp52** [comment]
Line 3:  \* Filename:    includes/lang/russian-UTF8.inc.php
is now incorrect - it's   includes/lang/russian.inc.php

A few questions:

196 - $_lang["database_table_engine"] = 'Engine';
is not translated. Is this "Тип" in Russian?

250 - $_lang['package_manager_upload_byfolder_label'] = 'Прочитать пакет из каталога';
This option is to install an Extra from an uncompressed folder, for use during development, so I think it should read something like "Загрузить с папки" (unless I've misunderstood the Russian)

252 - $_lang['package_manager_restart'] = 'Вернуться в начало менеджер пакетов';
Should that read 'Вернуться в начало менеджера пакетов' ?

260 - $_lang['package_manager_error_internal'] = 'Внутренняя загрузка ошибки. Пожалуйста, попробуйте еще раз.';
Should that read 'Внутренняя ошибкa при загрузке....' ?

Спасибо большое за эту работу!

**Comment by rellai** [comment]
Не за что, хоть чем то рад помочь проекту!!
196 - $lang["databasetable_engine"] = 'Ядро СУБД';
250 - $lang['packagemanager_upload_byfolder_label'] = 'Загрузить из папки';
252 - $lang['packagemanager_restart'] = 'Вернуться в начало менеджера пакетов';
260 - $lang['packagemanager_error_internal'] = 'Внутренняя ошибкa при загрузке. Пожалуйста, попробуйте еще раз.';
