### ISSUE TITLE
Invalid path to image for manager theme

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#403]
Getting a missing file note in my server logs when in the manager interface for modern theme. Cause is in manager/media/style/common/styles.css (line 282):

background-image:url(images/misc/tabareabg.gif);

This css file is called by manager/frames/tree.php (line 24) and resolving the path for the image to:

manager/media/style/common/images/misc/tabareabg.gif 

which does not exist.

**Comment by kp52** [comment]
What version of Clipper? The file is certainly there in the 1.2.6 distribution.

**Comment by TimGS** [comment]
The image is in style/ClipperModern, but the CSS link is in style/common.

Although very much a work in progress, style/common is meant to be a basic style that is always included and themes build on this foundation. I think this CSS rule is non-essential, and as such belongs with ClipperModern - i.e. the CSS rule with that link should be moved back to ClipperModern. Agreed?

-- Tim.

**Comment by bossloper** [comment]
Tim - Yes that sounds correct to me!

p.s. the 'Download ClipperCMS 1.2.6' button on the ClipperCMS site does not seem to be working for IE11 (fine for Chrome, Firefox etc)

**Comment by microcipcip** [comment]
IE doesn't finish to surprise me! I'll check out why it doesn't work, thanks!

**Comment by microcipcip** [comment]
It seems to be a security setting of IE http://answers.microsoft.com/en-us/ie/forum/ie8-windows_other/error-message-your-current-security-settings-do/59cc236d-7baf-4552-92ff-b34b9a6942aa

**Comment by TimGS** [comment]
I think this is fixed in branch 1.2.x, which will shortly be 1.2.7. If I'm wrong, re-open!

**Comment by Cipa** [comment]
This is not fixed in 1.2.9, there are 3 solutions
1. remove the gif from both themes and common theme file
2. add the gif to common theme (we now have 3 tabareabg.gif)
3. remove the gif from the common theme (simplest)

I implemented 3 on a local project
