### ISSUE TITLE
Res Manager: Make Russian-UTF8.inc.php the default language file for Russian

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#407]
Current default Russian language file for Res Manager is Windows Cyrillic 1251 coding. This doesn't work in Res manager main screen (just "unrecognized character" symbols). Changing file name of russian.inc.php to russian-1251.inc.php and then russian-UTF8.inc.php to russian.inc.php fixes this.
(Sorry no time to process as pull request)

**Comment by TimGS** [comment]
Sort of fixed, though on 1.2.x this inherently breaks it for a character encoding of 1251 when set via Tools->Config.

In develop this is fixed properly!
