### ISSUE TITLE
MultiTV problem with image thumb

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#409]
I have found a bug with MultiTV when used in "datatable" view. When I insert an image, the view scroll on top of the page, and I have to go down to insert more imgs. I have analized with firebug the code of the input field for the image path, and this is what I see:

```
<input 
    type="text" 
    onchange="documentDirty=true; if (!this.value) $('#tv0-preview img').fadeOut(500).slideUp({duration: 500, queue: false, complete: function () { $('#tv0-preview').html(''); }});" value="" name="tv181img5_mtv" id="tv181img5_mtv"
    class="img5 image image-preview"
>
```

If I delete from class="img5 image image-preview" the "image" class, it doesn't do this anymore, however I don't see the thumb preview now. Does anyone know what is all the code in the "onchange"? Just code for hiding the image if it has been changed?

**Comment by TimGS** [comment]
May be best to ask in the forums.

**Comment by microcipcip** [comment]
Ok.

**Comment by Jako** [comment]
The class names `image image-preview` are set by multiTV. If that causes an issue, the naming of those class names could be changed in multiTV php/javascript code to something more unique like `mtv-image mtv-image-preview`.

**Comment by TimGS** [comment]
I think that would be a reasonable solution.

**Comment by Jako** [comment]
Should be solved with https://github.com/Jako/multiTV/releases/tag/2.0.1
