### ISSUE TITLE
Quick manager is missing some files

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#41]
Hi,

Seems like some files needed for QM are missing

here are the paths
asstes/js/images/controls.png
asstes/js/images/border.png
asstes/js/images/loading_background.png
asstes/js/images/ajax-loader.png

Maybe they should be placed in the QM plugin folder

**Comment by TimGS** [comment]
Possibly not - are they colorbox (jquery plugin) files?

**Comment by Cipa** [comment]
Yes, I think so, Qm is using ColorBox

**Comment by TimGS** [comment]
Fixed. 

I'd previously moved colorbox.css into the generic assets/js folder, assuming it was an entirely generic colorbox file. I've now moved it back to the qm folder, where it's images are. 

Its not really a pure colorbox CSS file - it appears to be a slightly changed CSS file from one of the colorbox examples in the current colorbox download.
