### ISSUE TITLE
Output Modifiers - ;limit()

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#410]
Does the limit output modifier work with List? I have tried the following but I don't see any output:
[+content;limit(15)+]
[+content;html;limit(115)+]

**Comment by TimGS** [comment]
Do the other modifiers definitely work e.g. ;html ?

**Comment by microcipcip** [comment]
It doesn't, I guess some conflict with PHx, I will try to test with the plugin disabled.

**Comment by microcipcip** [comment]
There is a strange behaviour, with PHx enabled I can work with Cross References and not with Output modifiers, and when I disabled PHx even Cross References stop working, I will make a clean install of ClipperCMS, maybe there is a conflict somewhere with the plugin.

**Comment by microcipcip** [comment]
I have installed a clean copy of ClipperCMS 1.2.6. Output modifiers (at list limit) are working outside List, but not inside List template. PHx is disabled.

**Comment by TimGS** [comment]
I think it's fixed in the develop branch. Try it and see.

**Comment by microcipcip** [comment]
Ok, I'll try.

**Comment by TimGS** [comment]
#413 now fixed, so #410 should be now testable.

**Comment by TimGS** [comment]
Put &phx=`0` in the snippet call. Perhaps this should now be the default?

**Comment by TimGS** [comment]
I've also added https://github.com/ClipperCMS/ClipperCMS/commit/71740baeb3e5d21e084842a4eef11e02cdbad5b2, which should make &phx=`0` unnecessary.

Now each single list/ditto template can use phx or output modifiers - but not both within the same template.

This is in the develop branch. Stable branches (i.e. 1.2.8) will still need &phx=`0`.
