### ISSUE TITLE
RSS feeds in manager not working

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#419]

**Comment by kp52** [comment]
Replacement using SimplePie reader in place of MagieRSS and suitable URLs for FluxBB in context of 1.2.x is now available at https://github.com/kp52/ClipperCMS/tree/RSS
Tested on local PC/Apache/PHP 5.5.4 only so far. Will be testing on Linux server shortly.

**Comment by kp52** [comment]
Now tested on Linux server + PHP 5.3.2

**Comment by kp52** [comment]
Also need to update setup.sql for new addresses - <del>coming up</del> **done**!
