### ISSUE TITLE
1.2.7 upgrade install fails

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#422]
Changed line 286 in install/instrocessor.php

```
$database_type = \''.$_POST['phpdbapi'].'\';
```

expects to receive value from mysql/mysqli choice that is so far only in Develop. As it stands, it's blank, and destroys the database type setting in config.inc.php on an upgrade install. 

Haven't tested a fresh install yet.

For now, this should either revert to 1.2.6's 

```
$database_type = \'mysql\';
```

or make mysqli the default 

```
$database_type = \'mysqli\';
```

(after all, you must have mysqli active to get this far, with other changes that exist earlier in the process).

**Comment by kp52** [comment]
Fresh download today has 

```
$database_type = \'mysql\';
```

So I must have picked up wrong file somehow. All the same, this could usefully be updated to set mysqli as the default, or detect and preserve existing config.inc.php setting on upgrade. Testing with PHP 5.5.3, I get "deprecated" errors that prevent login after install or upgrade install until config.inc.php is manulally edited.

**Comment by TimGS** [comment]
Maybe it should set mysqli only for PHP 5.5 and higher.

I think earlier versions should keep mysql as the default until version 1.3.

-- Tim.

**Comment by kp52** [comment]
I can live with that, if 5.5 is when PHP starts raising objections, though I see no advantage, now that all core files use DBAPI. 

So instprocessor needs to check, in priority order:
- (future Clipper versions) setting requested in initial settings screen of fresh install
- existing setting in config.inc.php to be preserved (upgrade install)
- PHP version to select mysql (&lt;5.5) or mysqli (&gt;=5.5)

**Comment by TimGS** [comment]
Not sure offhand, but I think the first two may be already in develop.

Maybe for 1.2.7 just do the third check?

-- Tim.

**Comment by kp52** [comment]
First is in develop (POST data, and cause of my original confusion)
I think the second is there (set in action.options.php)
(Updated my previous comment to show &lt; and &gt; properly)

**Comment by TimGS** [comment]
First two seem to be in _develop_ via https://github.com/ClipperCMS/ClipperCMS/commit/aeeea7d69486ab412ec973f4b7b6f82461ee6c40

-- Tim.

**Comment by TimGS** [comment]
I'm having second thoughts - maybe we should cherry-pick this commit into 1.2.x (?).

Existing sites retain mysql on the quick upgrade. New sites and existing sites on the advanced upgrade get the choice with mysqli being the default.

Maybe a note could be added to the action=mode stage to pick advanced upgrade if experiencing problems with PHP 5.5 and mysql? Alternatively we could have a new upgrade option that is like the quick upgrade but sets mysqli in the config?

**Comment by kp52** [comment]
Tested transplant of Develop's installer into 1.2.x (fresh downloads from this morning) (unselective apart from replacing newer setup.sql), so I was installing 1.2.x with choice of myqsql(i). Used PHP 5.5.4 with no mysql etension for mysqli-only setup, and PHP 5.2.17 with mysql & mysqli extensions to test switching.
- choice of mysql(i) offered on new install, and choice is implemented
- upgrade install preserves mysql/mysqli setting
- advanced install offers choice again, and it works in both directions

Using Advanced upgrade purely to switch extension means having a lot of data to hand, and entering it accurately, so the balance is in favour of adding an option to the Upgrade install. Or maybe a checkbox (default selected) to switch to mysqli if the installer detects mysql is current setting? You're not starting a whole new type of installation by doing the switch.

**Comment by TimGS** [comment]
Checkbox seems the best option, especially as this feature probably has a limited lifespan as per PHP's mysql extension.

I have cherry-picked aeeea7d69486ab412ec973f4b7b6f82461ee6c40 into 1.2.x

**Comment by kp52** [comment]
Have used current 1.2.x for a transfer from MODX to Clipper. Choice of mysql/mysqli in initial setup, and preservation of choice through upgrade installs, working fine.
