### ISSUE TITLE
RSS feeds in manager

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#423]
In 1.2.7, I now see only News->Extras in both News and Security feeds

I can't see News or Security feeds at all.

In the config I have:
RSS news feed: http://www.clippercms.com/forum/index.php?board=3;type=rss;action=.xml;sa=news;limit=20

RSS security feed: http://www.clippercms.com/forum/index.php?board=22;type=rss;action=.xml;sa=news;limit=20

-- Tim.

**Comment by kp52** [comment]
You should see the FluxBB announcement. with the config in the install package.
1.2.7 announcement is missed and security notices is blank (no default message) because of error in rss.inc.php:
Lines 57-63 should read

```
if (strlen($description) > 199) {
    $description = substr($description, 0, 200);
    $description .= '...<br />Read <a href="' . $link . '" target="_blank">more</a>';
}
$output .= '<li><a href="' . $link . '" target="_blank">'
. $title . '</a> - <b>' . $pubdate . '</b><br />'
. $description . '</li>';
```

otherwise shorter items are skipped.

**Comment by kp52** [comment]
Correct RSS strings for config are:

```
http://www.clippercms.com/forum/extern.php?action=feed&fid=3,31&type=rss&order=posted
```

and

```
http://www.clippercms.com/forum/extern.php?action=feed&fid=22&type=rss&order=posted
```
