### ISSUE TITLE
OnDocUnPublished/OnDocPublished not triggered when documents are unpublished automatically

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#429]
Hi,

Unless I misunderstood the scope of OnDocUnPublished/OnDocPublished events, these events are not triggered when a doc is unpublished when a set unpub_date date is set.

I think that around line 812 in manager/includes/document.parser.class.inc.php we need a way to trigger the OnDocUnPublished/OnDocPublished events, problem is modx object is not available there so I am not sure what is the best way to go fwd.

Thank you

**Comment by Jako** [comment]
Maybe it is solved here: https://github.com/modxcms/evolution/pull/67

**Comment by TimGS** [comment]
Agree with putting it in DocumentParser::checkPublishStatus(). This seems logical and consistent with it's current use in the manager i.e. publish/unpublish when _only_ that is happening.

I don't think it should go in the save content processor as per the pull request to MODx. Plugins already exist that work on the basis that either the save document events are being invoked or the publish events are being invoked - but not both.

-- Tim.

**Comment by Cipa** [comment]
Thanks, I implemented the solution above on a older version of clipper and it seems to work.

**Comment by TimGS** [comment]
Implemented in DocumentParser::checkPublishStatus()
