### ISSUE TITLE
JOT call to missing function in Clipper 1.2.9

### ISSUE THREAD

**Issue by ghost** [ClipperCMS/ClipperCMS#432]
Snippet Jot has a call in jot.class.php (line 496 and  line 898) to a function $modx->htmlspecialchars which does not exists in Clipper.

**Comment by TimGS** [comment]
We need someone to step up and maintain Jot!

-- Tim.

**Comment by Jako** [comment]
$modx->htmlspecialchars is just a wrapper for htmlspecialchars with the MODX charset.

**Comment by TimGS** [comment]
Am fixing this now in the develop branch.

**Comment by TimGS** [comment]
See https://github.com/ClipperCMS/ClipperCMS/commit/6ca67bbe9339116320c399cda907ca721792d5e4
