### ISSUE TITLE
Develop (1.3): transalias plugin file missing

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#433]
After installing current Develop branch with all snippets and other elements, I get an error on saving a resource:
Warning: require(H:/EBMS/assets/plugins/transalias/plugin.transalias.php): failed to open stream: No such file or directory in H:\EBMS\manager\includes\document.parser.class.inc.php(1274) : eval()'d code on line 1 Fatal error: require(): Failed opening required 'H:/EBMS/assets/plugins/transalias/plugin.transalias.php' (include_path='.;C:\php\pear;H:/EBMS/manager/includes/') in H:\EBMS\manager\includes\document.parser.class.inc.php(1274) : eval()'d code on line 1

Between 1.2.9 and current Develop, plugin code has changed to require the missing file.

**Comment by TimGS** [comment]
Fixed.
