### ISSUE TITLE
Develop(1.3) + List 2.1.3 spurious language warnings

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#434]
Using List 2.1.3 with current Develop branch, I'm getting two warnings logged in System Events for each List call:

Language file cannot be completely converted to UTF-8. Please check: ..../assets/snippets/list/lang/english.inc.php 

As far as I know, everything is already UTF-8. Maybe some mismatch in document parser convertLanguageArray() ?

**Comment by TimGS** [comment]
DocumentParser::convertLanguageArray() returned the wrong/illogical success/fail values.
