### ISSUE TITLE
List + PHx modifiers

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#435]
Using current develop branch, I have a List call with a PHx modifier in the tpl chunk, e.g.
[+introtext:myModifier=`[+content+]`+]

The "content" placeholder's value should appear in the snippet **phx:mymodifier** as $options. But it doesn't. Exploring a little with variations on this theme, such as adding more placeholders to the options string, it looks as if the data for the first placeholder in the PHx modifier options string is lost. 

Needs further investigation: is this a new phenomenon?

**Comment by TimGS** [comment]
Don't know  - I avoid phx.

**Comment by TimGS** [comment]
I think perhaps we need a discussion on whether we should support phx.

**Comment by nick0** [comment]
If PHx is not going to be supported by ClipperCMS, please provide a nice alternative that works in html and snippet templates.
PHx allows a lot of flexibility, particularly in templating, that cannot otherwise be easily achieved (well, at least without programming knowledge).
I never do any web project without it.

**Comment by kp52** [comment]
At the risk of making UK-culture-specific references, the PHx plugin is similar to Marmite (you love it or you loathe it), and "I agree with Nick": PHx as an auxiliary to List (and several other snippets) is indispensable in template chunks. Whatever the case, the place to discuss it is in the forum. This issue concerns an apparent bug that I intend to investigate further in its own right.

**Comment by TimGS** [comment]
I will post on the forum, but to close this part of the discussion, a few points should be clear.
- if it's a bug with ClipperCMS or List, we will fix it. 
- if it's a bug with Phx, someone needs to maintain phx! Phx is not core code.
- if it's a conflict with new ClipperCMS development and Phx, then people need to accept that something needs to give somewhere.

-- Tim.

**Comment by kp52** [comment]
Using specific tests with a List/Ditto template chunk in Clipper-develop, Clipper 1.2.8 and MODX-1.0.15, I find that:
no value is submitted to a PHx modifier for [+content+] when it is the first argument for the modifier, e.g.

```
[+phx:myModifier=`[+content+]||[+pagetitle+]`+]
```

**unless** the [+content+] tag is included elsewhere in the template chunk.

"elsewhere" may be as a later argument to the PHx tag, so this one works:

```
[+phx:myModifier=`[+content+]||[+pagetitle+]||[+content+]`+]
```

I'm sure I had a more general case where any placeholder as the first argument would fail, but haven't been able to reproduce that in the testing.

I am closing this issue as a "no need to fix" bug. It's doubtful whether using [+content+] in a PHx modifier is wise in any case. There are too many potential nesting issues.

**Comment by Jako** [comment]
List bases on Ditto: In Ditto there exists the &hiddenFields parameter, that fixed those problems.

**Comment by kp52** [comment]
I hadn't tried &hiddenFields before, but have now. It doesn't fix this problem, which seems to affect PHx's handling of placeholders, not Ditto/List's handling of templates. In fact I did manage to reproduce the general "first argument not processed" behaviour with [+longtitle+] and [+description+]. They are processed if also mentioned elsewhere in the template chunk, but not if their only appearance is as first PHx modifier argument.
