### ISSUE TITLE
DocManager/Template Variables/A template with a IMG tv still opens the old image browser

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#441]
Same thing could happen to other modules like ResManager

What is the correct approach to fix this? Is there a setting to change between the 2 image browsers and should we still keep the old one?

**Comment by microcipcip** [comment]
Is this a bug or you're experiencing this in all websites?

**Comment by Cipa** [comment]
It doesn't do it anymore, maybe something was cached after upgrade
