### ISSUE TITLE
this [[#fixes a chrome bug when vertically middle aligned]] generates a report

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#442]
Hi 
[[#fixes a chrome bug when vertically middle aligned]]
in a file generates a report in event log.

How are these parsed lately [[# ]]

Thank you

**Comment by TimGS** [comment]
As far as I am aware there were never any comments tags in Evo.

I think Revo has [[- ]] or something like that

**Comment by Cipa** [comment]
True, but should [[# ]] generate a report?

**Comment by TimGS** [comment]
Oh - sorry - I think I misunderstood - is it in a core file somewhere?

If in parsed source the parser would interpret it as a snippet call, and then throw an error.

-- Tim.

**Comment by Cipa** [comment]
I have the [[# comment]] in a template. The parser makes a report that 
`Snippet # comment missing or empty`

Same thing happens for [[-]]

We can think of this as a feature but would be nice to have a tag that doesn't throw errors in the system events section

**Comment by TimGS** [comment]
[[# ]] never was a comment tag - so the parser does indeed start looking for a snippet called '#', hence your error message.

Best put it as a feature request for 1.4.

-- Tim.

**Comment by Cipa** [comment]
Maybe we can use {{ This is a comment }}.
