### ISSUE TITLE
Using clipper/modx with dompdf

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#443]
Hi,

Unless I am missing something there is no way to turn off header being sent in document.parser.class.inc.php and use your own header. Here is an example

On a page with a blank template and rich text off put a snippet like this 

`````` <?php
require_once($modx->config['base_path'] . "assets/site/dompdf/dompdf_config.inc.php");

$html =
 '<html><body>'.
 '<p>Put your html here, or generate it with your favourite '.
 'templating system.</p>'.
 '</body></html>';

$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();
$dompdf->stream("sample.pdf");
?>```


Dom PDF generates it's own header and I get something like
Cannot modify header information - headers already sent 

The pdf downloads but it's not valid and contains a php error.

------

I tried various Resource Type/Internet Media File/Content-Disposition values but the header is always sent. Maybe we can add a setting where no headers are sent by document.parser.class.inc.php.

Thank you
``````

**Comment by TimGS** [comment]
IIRC, in PHP, even if headers have already been set, you can override them as long as the body output hasn't been started. So although I'm not entirely sure why your example doesn't work, in general this shouldn't be a problem.

Maybe the included dompdf file(s) have some superfluous spaces at either the start or end of the file?

Is render() generating output to the body?

--Tim.

**Comment by Cipa** [comment]
render should generate the html in the code in a pdf way
for an older clipper install I made it work with

```
if ($this->documentIdentifier != 742) {
                header('Content-Type: ' . $type . '; charset=' .
$this->config['modx_charset']);
            }else{

            }
```

Still trying to figure out the problem in the latest clipper

**Comment by Jako** [comment]
exit(); after the last line.

**Comment by Cipa** [comment]
Excelent, thank you
