### ISSUE TITLE
Use System Configuration Setting or Use Main Configuration Setting

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#447]
We should use one of them not both in the same section
See Create/Edit User/ User tab

Please let me know which one is prefered.

**Comment by TimGS** [comment]
Puzzled. Can you explain further? I'm not sure what you mean.
-- Tim.

**Comment by Cipa** [comment]
![screen shot 2015-03-28 at 1 27 34 pm](https://cloud.githubusercontent.com/assets/293377/6882029/363164ca-d54e-11e4-9140-a015509e5527.png)

The checkbox has a different text than the one in the note below the field

**Comment by TimGS** [comment]
I see. 'System config...' seems more logical to me.
