### ISSUE TITLE
Now that ckfinder is the prefered file browser shouldn't we switch to ckeditor?

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#450]

**Comment by TimGS** [comment]
I'm happy with TinyMCE - but this is a plugin, and so presumably you could write a plugin for ckeditor.

**Comment by Cipa** [comment]
There is one I think, I'm not ok with the current version of TinyMce(lots of webkit bugs, not their fault) but I might be with the new one
