### ISSUE TITLE
@parent feature request

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#451]
If [ \* pagetitle@1 \* ] works would be nice to have [ \* pagetitle@parent \* ] work as well.
Or maybe 

[ \* pagetitle@[ \* parent \* ] \* ]

Thx

**Comment by TimGS** [comment]
Have you tried [_pagetitle@parent_] ! ;-)

http://www.clippercms.com/documentation/construction/cross-references.html

-- Tim.

**Comment by Cipa** [comment]
Doesn't seem to work if the parent is 0. I get "pagetitle@parent" instead of "Home"
Works for pages inside other documents

Update: I am not sure what it's supposed to do if the parent is 0 but it should not output pagetitle@parent, maybe nothing would be better

**Comment by TimGS** [comment]
If parent is zero, the parent doesn't exist, implying the output should be empty.

**Comment by Cipa** [comment]
I see pagetitle@parent  when I put [ \* pagetitle@parent \* ] on a root page.

**Comment by TimGS** [comment]
branch clipper-1.3.x
