### ISSUE TITLE
ManagerManager is missing some features

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#455]
See
http://code.divandesign.biz/modx/mm_ddcreatesection/1.0

Any reason why they are not included? Maybe not compatible with Clipper?

**Comment by TimGS** [comment]
Don't know offhand. Never come across mm_ddCreateSection before. Perhaps it post-dates the fork date.

This doesn't really seem like an issue as such, so I'm closing, but if anyone wishes to code/port this to Clipper and it works with no negative side effects, I'm sure it could be merged without any issues.
