### ISSUE TITLE
eform warning

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#456]
preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead; File: /home/myworkspot/public_html/sample/manager/includes/protect.inc.php; Line: 42 

PHP:5.5.23
![screen shot 2015-05-05 at 12 29 39 pm](https://cloud.githubusercontent.com/assets/293377/7477536/787ae38c-f322-11e4-88e0-ebb13a774d75.png)

**Comment by TimGS** [comment]
Can you fix and make a pull request on branch clipper-1.3.x?

**Comment by Cipa** [comment]
not sure this is the best way, can you have a look first

```

if (!function_exists('modx_sanitize_gpc')) {
    function modx_sanitize_gpc(& $target, $modxtags, $limit= 3) {
        foreach ($target as $key => &$value) {
            if (is_array($value) && $limit > 0) {
                modx_sanitize_gpc($value, $modxtags, $limit - 1);
            } else {
                while (true) {
                    $matched = 0;
                    //$value = preg_replace($modxtags, "", $value);
                    $value = preg_replace_callback($modxtags, 'replaceWithAnEmptyString', $value);
                    foreach ($modxtags as $tagPattern) {
                        if ($matched = preg_match($tagPattern, $value)) {
                            break;
                        }
                    }
                    if ($matched > 0) continue;
                    break;
                }
                $target[$key] = $value;
            }
        }
        return $target;
    }

    function replaceWithAnEmptyString($matches) {
        return '';
    }
}

```

**Comment by TimGS** [comment]
Hmmm. Which branch is this on?

It doesn't appear to be an issue on clipper-1.3.x and also rings a bell. I think it's been fixed already.

-- Tim.

**Comment by Cipa** [comment]
these are the lines 
 //$value = preg_replace($modxtags, "", $value);
$value = preg_replace_callback($modxtags, 'replaceWithAnEmptyString', $value);

I could not find the fix on develop

**Comment by Cipa** [comment]
Also, if you want to test this
- make sure you have PHP:5.5.23
- a form using eFrom

For me at least the warnings stopped with the upgrade above, let me know if you need more server details. If you are ok with teh code I will submit a patch

**Comment by Cipa** [comment]
hold on this, the warning is gone but some other error appeared
I get
 Error:     preg_replace_callback(): Modifier /e cannot be used with replacement callback    

Which is weird as there is no /e, I'm sure I am missing something

**Comment by TimGS** [comment]
commit c336a99c37fea9adf0835500b8101a4a4e7968ca removed the /e modifier from $modxtags in protect.inc.php.

I think something is up with either your system or your diagnosis.

**Comment by Cipa** [comment]
I did not have an e, which makes things weirder. The Warning only appears when you run the form and I get 11 of them every time I try to submit the form
![screen shot 2015-05-06 at 9 16 13 am](https://cloud.githubusercontent.com/assets/293377/7493618/8fa61f46-f3d0-11e4-820e-f50d2540c716.png)

**Comment by Cipa** [comment]
Any ideas why the @ character is needed. I could not find anything online about it.

**Comment by Cipa** [comment]
Found a fix(for me at least)

if I put the modxtags array in the preg_replace call the warning disappears

```
$value = preg_replace(array ('@<script[^>]*?>.*?</script>@si','@&#(\d+);@','@\[\~(.*?)\~\]@si','@\[\((.*?)\)\]@si','@{{(.*?)}}@si','@\[\+(.*?)\+\]@si','@\[\*(.*?)\*\]@si','@\[\[(.*?)\]\]@si','@\[!(.*?)!\]@si'), "", $value);
```

Weird as this snippet doesn't seem to cause any warnings

```
<?php
$modxtags = array (
    '@<script[^>]*?>.*?</script>@si',
    '@&#(\d+);@',
    '@\[\~(.*?)\~\]@si',
    '@\[\((.*?)\)\]@si',
    '@{{(.*?)}}@si',
    '@\[\+(.*?)\+\]@si',
    '@\[\*(.*?)\*\]@si',
    '@\[\[(.*?)\]\]@si',
    '@\[!(.*?)!\]@si'
);

$value = '<script>var a= 1;</script>';

$value = preg_replace($modxtags, "XXX", $value);

echo '---' . $value . '---';
?>
```

**Comment by TimGS** [comment]
The '@' is simply the regular expression delimiter. Convention has it more commonly as '/', but it can be (AFAIK) absolutely anything and is signalled by the first character (or byte perhaps - not sure which) of the regex string.

I wonder if the error reporting is correct in where the error is being reported. Take a closer look at the Eform code.

**Comment by Cipa** [comment]
I looked at the eform code. I could not find any /e or any includes of protect.inc.
Must be something else

**Comment by Cipa** [comment]
The problem comes from eform.inc.php line 193, there is an e I missed in my previous searches.
Let me know if you need a pull request

**Comment by TimGS** [comment]
I will need a pull request to clipper-1.3.x.

**Comment by Cipa** [comment]
done
