### ISSUE TITLE
Incompatibility with MySQL 5.7

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#465]
Recently installed local web server has Xubuntu 16.04, PHP 5.6, Apache 2.4 and **MySQL 5.7.12**. 

Editing local copy of sites, TVs don't show up in the Edit screen, and changes are not saved. No error is displayed, but the log contains "parse errors" such as: 

> « **Execution of a query to the database failed - Expression #1 of ORDER BY clause is not in SELECT list, references column 'mydb.tvtpl.rank' which is not in SELECT list; this is incompatible with DISTINCT** »
>       SQL: SELECT DISTINCT tv.*, IF(tvc.value!='',tvc.value,tv.default_text) as value FROM `mydb`.`jl_site_tmplvars` AS tv INNER JOIN `mydb`.`jl_site_tmplvar_templates` AS tvtpl ON tvtpl.tmplvarid = tv.id LEFT JOIN `mydb`.`jl_site_tmplvar_contentvalues` AS tvc ON tvc.tmplvarid=tv.id AND tvc.contentid='1' LEFT JOIN `mydb`.`jl_site_tmplvar_access` AS tva ON tva.tmplvarid=tv.id WHERE tvtpl.templateid='4' AND (1='1' OR ISNULL(tva.documentgroup)) ORDER BY tvtpl.rank,tv.rank, tv.id

Apparently caused by deprecated features in MySQL 5.7, where "ONLY_FULL_GROUP_BY" is a default setting. cf [related MODX Revolution issue ](https://github.com/modxcms/revolution/issues/12401)

Resolved for now by adding following to my.cnf file to remove ONLY_FULL_GROUP_BY settings (and also STRICT_TRANS_TABLES, which prevented ProcessWire installer from working):

```
# disable strict table checks etc.
[mysqld]
sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

```

**Comment by TimGS** [comment]
As a workaround, can we run SET SESSION sql_mode = '' after connecting to the database?

**Comment by TimGS** [comment]
I think this is half fixed. It's in the DBAPI, but the installer still has a warning, now incorrect.

**Comment by TimGS** [comment]
install/ now updated.
