### ISSUE TITLE
unpub_date setting ineffective in Clipper 1.3.1

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#467]
SQL query starting on line 858 needs to retrieve the `published` field for the test on line 864 to be meaningful. Otherwise published items due for unpublishing continue to be marked as published.

Change
`$results = $this->db->makeArray($this->db->query("SELECT id FROM {$this->getFullTableName('site_content')}`
to
`$results = $this->db->makeArray($this->db->query("SELECT id, published FROM {$this->getFullTableName('site_content')}`

**Comment by TimGS** [comment]
Filename?

**Comment by kp52** [comment]
`document.parser.class.inc.php`
