### ISSUE TITLE
Clipper 1.3.1: phpmailer 5.2.12 SMTP autoloader issue

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#469]
Upgrade from v 5.2 of phpmailer in Clipper 1.3.0 to v 5.2.12 in Clipper 1.3.1 means you are required to include the SMTP class file explicitly or set up an autoloader, if you want to use SMTP. 

From notes accompanying release PHPMailer 5.2.9:

> The autoloader is no longer autoloaded automatically, and the PHPMailer class does not require the SMTP class explicitly, so you must either load the autoloader yourself (as all the docs and examples have done for the last year), or load the SMTP class yourself. This fixes the inability to substitute your own SMTP subclass, and also improves interoperability with other autoloaders.

I'm not familiar with autoloaders, but I found that adding the PHPMailer project's [PHPMailerAutoload.php](https://github.com/PHPMailer/PHPMailer/blob/master/PHPMailerAutoload.php) file to manager/includes/controls/ alongside the main class.phpmailer.php file, and adding `require 'PHPMailerAutoload.php';` at the top of that file, got SMTP working for me again.

**Comment by TimGS** [comment]
Can you submit a pull request to develop?
ta,
-- Tim.

**Comment by kp52** [comment]
Will do that

**Comment by TimGS** [comment]
Pull request merged.
