### ISSUE TITLE
Duplicate a resource - empty TVs

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#51]
Hi,

seems like when I try to duplicate a resource all the TVs are empty. Any ideas?

**Comment by TimGS** [comment]
Fixed. A silly bug in the new insert functionality in the DBAPI.

https://github.com/ClipperCMS/ClipperCMS/commit/3c01c99aaa78b75e642144fd034995f90c2421e7

**Comment by Cipa** [comment]
I don't get it. Why it was doing that?

Thanks

**Comment by TimGS** [comment]
Too much copying and pasting!

See the commit. The optional parameters where never being passed to __insert().

**Comment by Cipa** [comment]
I get it now. It was the beer :)

**Comment by microcipcip** [comment]
http://xkcd.com/323/

**Comment by Cipa** [comment]
:)
