### ISSUE TITLE
Database coalition utf-8

### ISSUE THREAD

**Issue by fourroses666** [ClipperCMS/ClipperCMS#57]
I don't know much about it but when i want to use Russian or Chinese / Japanese text the database coalition needs to be utf-8.

Somehow on every install it is latin1_swedish_ci even when i don't pick that on install.

Lately i had to change them all by hand, I dunno if it is something that can be changed but i think it always needs to be utf-8 global or something?

**Comment by TimGS** [comment]
Easiest short term workaround is to always create your database with a default UTF-8 collation (which arguably isn't a workaround as it's what should be done anyway if you are using UTF-8). Use the following SQL:

CREATE DATABASE fourroses_modx CHARACTER SET utf8 COLLATE utf8_general_ci

That aside, I'll look into what we can do in the install script for 1.2.

-- Tim.

**Comment by fourroses666** [comment]
Oke sounds good with me Tim.

---

Never play arround with SQL, just did try your sql line into phpmyadmin.
I get a #1044 - Access denied for user... so guess i don't have root privileges.

Are there any workarounds you know of? I always make my db with direct admin.

**Comment by TimGS** [comment]
http://www.clippercms.com/docs/installation

**Comment by fourroses666** [comment]
Indeed, looks like this works, it didn't gave any permission problem on the shared hosting db:

ALTER DATABASE my_dbnamehere CHARACTER SET utf8 COLLATE utf8_general_ci; 
- haven't installed any cms on it yet.

**Comment by fourroses666** [comment]
Maybe this helps?

http://wiki.modxcms.com/index.php/De:MODx_f%C3%BCr_den_Betrieb_unter_UTF-8_einrichten

(it's german)

**Comment by TimGS** [comment]
The installer (develop branch) will now create the tables in your specified character set and collation, regardless of the database default.

This is not intended as a substitute for creating the database with the correct character set and collation in the first place - but it will assist people such as yourself who do not have the permissions to change the database character set on a shared host, and wish to develop directly on that host (not recommended - I suggest developing on your local machine first).
