### ISSUE TITLE
FCKeditor Resource Browser and IE10

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#58]
Running IE10 under technet Windows 8 evaluation version.

The FCKeditor is not showing any files or folders unless the IE10 'compatibility view' icon is clicked.

A fix is to add:

 <meta http-equiv="X-UA-Compatible" content="IE=8;FF=4;OtherUA=4" />

to the manager/media/browser/mcpuk/browser.html file. This also make it consistent with the fix added to the manager index.php file recently.

**Comment by TimGS** [comment]
Line added. Can you test?

**Comment by bossloper** [comment]
Tested.... failed because I made a mistake, sorry. 
The line needs adding to the 'inc' file, not the 'html' file: manager/media/browser/mcpuk/browser.html.inc

I am not sure if/when the browser.html file is used? Maybe the line needs to stay there too.

**Comment by TimGS** [comment]
Done. Can you test again?

browser.html still contains the line, as we should be consistent across the manager.

**Comment by bossloper** [comment]
yes working now.

**Comment by TimGS** [comment]
Thanks.
