### ISSUE TITLE
Maximum upload size not honoured correctly

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#60]
The system configuration 'Maximum upload size' is set by default to 1048576 bytes which is 1 Megabyte. This sounds fine. But when I upload a large image file (say 4 Megabytes) it is still getting uploaded. I checked the mcpuk code and on line 57 of manager/media/browser/mcpuk/connectors/php/Commands/FileUpload.php there is the following:

if ($_FILES['NewFile']['size']<($typeconfig['MaxSize']*1024)) {

That line is multiplying the max size by 1024 so my max size limit is never reached. If I take the *1024 out it behaves as I would expect.

if ($_FILES['NewFile']['size']<($typeconfig['MaxSize'])) {

**Comment by TimGS** [comment]
Also need to transfer this to kcfinder, if we wish to keep it. Alternatively we could dump the feature entirely (I suspect it causes more head scratching than it does help).

**Comment by TimGS** [comment]
I have implemented your fix for mcpuk.

This config setting does not currently apply to kcfinder.

**Comment by bossloper** [comment]
Personally, I think the maximum upload size should definitely be transferred to KCFinder. 

Without it users can upload huge files and if on a tightly limited hosting package bring a site down without knowing it.  It at least gives a 'sanity' upper limit that can be set by the admin to guide those site managers who may have no clue about file sizes and the potential impact.
