### ISSUE TITLE
Snippet weblogin english messages hardcoded

### ISSUE THREAD

**Issue by ghost** [ClipperCMS/ClipperCMS#67]
This snippet must be rewritten for the use of language files.

**Comment by TimGS** [comment]
As per https://github.com/ClipperCMS/ClipperCMS/issues/68, this is probably not something for the core group, though for slightly different reasons.

Although this snippet enables the web users core functionality, the core group has already taken on the more powerful and more useful WebLoginPE (our fork is named WebUsers). There is little point in maintaining two Extras that do the same thing, and WebLoginPE/WebUsers is the better developed of the two. Just to underline this point, WebLoginPE/WebUsers already uses language files.

If someone in the community wishes to upgrade weblogin to use language files then I cannot see any objection, but it would be reinventing the wheel. Easier to just switch to WebLoginPE/WebUsers!
