### ISSUE TITLE
Snippet jot english messages hardcoded

### ISSUE THREAD

**Issue by ghost** [ClipperCMS/ClipperCMS#68]
This snippet must be rewritten for the use of language files.

**Comment by TimGS** [comment]
This would be worth posting in the forums under 'Feature Requests'. As it concerns an 'Extra', albeit one currently bundled with the default install, it is probably not something for the core group.

So far the only Extras we have modified are Ditto (renamed List as it is now a fork) and WebLoginPE (renamed WebUsers). In both cases the modifications have been bugfixes. Ditto/List is sufficiently important to be regarded as having 'core functionality'  - most sites use it - and as such we have took on its maintenance. WebLoginPE is also concerned with core functionality, as although a snippet it enables use of the web users core functionality.

In the interests of our own workload we have to be selective in the Extras we take on, but we would welcome a solution to Jot and language files from the community - ideally from someone who is willing to take on ongoing maintenance of Jot. It may be worth trying to contact the original author and finding out if they intend to carry on development of Jot themselves.
