### ISSUE TITLE
image missing

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#69]
When I try to access the manager login page I see this in firebug

"NetworkError: 404 Not Found - http://hireiehps.com/manager/media/style/ClipperModern/images/input-bg.gif"

Thx

**Comment by TimGS** [comment]
Fixed. I've copied the corresponding image from ClipperCarbon.

thanks.

**Comment by Cipa** [comment]
Thx

**Comment by Cipa** [comment]
Maybe we should remove the image from the css and use a nice css gradient. Let me know if you want this reopened or maybe you want me to contribute. Thanks
