### ISSUE TITLE
Extra alert in js?

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#70]
Is the alert in the function below correct?
you can find it in 2 places manager/media/style/theme/html/login.html

`function ajaxReturn(response) {
            var header = response.substr(0,9);
            if (header.toLowerCase()=='location:') top.location = response.substr(10);
            else {
                var cimg = $('captcha_image');
                if (cimg) {
                 cimg.src = 'includes/veriword.php?rand=' + Math.random();
                }
                $$('input').removeProperty('readonly');
                alert(response);
            }
        }`

**Comment by TimGS** [comment]
Not sure. I've never seen a captcha image on a login page, and don't see why one would be required.

The wrong password/username alert seems to work though.

-- Tim.

**Comment by Cipa** [comment]
Was the js in the login.html changed? I have issues with it. Weird stuff
Locally everything is fine but live the alert was returning the path to the manager "http://sitename.com/manager" and the page would stay on the login form. The login information was correctly processed but no redirect.  

The manager is accessible if I reload the page as the connection was established at submit.

Tested in firefox and chrome. No redirect in both and the alert returns the path to the manager. In Chrome I get this error: Refused to set unsafe header "Connection"

Any ideas?

**Comment by Cipa** [comment]
I found the problem but I'm not sure how to fix it. I think the problem in the login.processor.php.

At least on one server this line "echo $header;" returns a string that has a space in front of "Location:......". I managed to remove it in js. see response = response.replace(/^\s+|\s+$/g,'');

Now the ideea is to remove it from php but I don't know how, yet. Any ideas?

```function ajaxReturn(response) {

``````
        var response = response.replace(/^\s+|\s+$/g,'');
        var header = response.substr(0,9);

        if (header.toLowerCase() == 'location:'){
            top.location = response.substr(10);
        }else {
            var cimg = $('captcha_image');
            if (cimg) {
                cimg.src = 'includes/veriword.php?rand=' + Math.random();
            }
            $$('input').removeProperty('readonly');
            alert(response);
        }
    }```
``````

**Comment by TimGS** [comment]
That looks like an adequate and pragmatic workaround for now, even if it is unsettling not knowing why it is required.

login.processor.php needs rewriting anyway for 1.2. Its quite different in action from the other processor/ scripts in how it is invoked (it is called directly), which has already caused some problems. As such, I really  wouldn't worry unduly about it for now - a temporary fix seems appropriate in these circumstances.

If you create a pull request I'll merge it later on.

thanks.

**Comment by Cipa** [comment]
Having issues trying to fork and send pull requests. I though I could use GitHub for Mac App but something is wrong. I will probably have to do it in the terminal and push the changes to you. I still have to figure out how to do it.

**Comment by TimGS** [comment]
Commited. Can you check all is now OK with both themes and let me know?

**Comment by Cipa** [comment]
works
