### ISSUE TITLE
ManagerManager

### ISSUE THREAD

**Issue by ghost** [ClipperCMS/ClipperCMS#74]
In the preferences of the plugin the configuration-chunk sould be changed from mm_demo_rules to mm_demo_rules-1_1.

If a very old mm_demo_rules exists in database the following managermanager-error occures on each page: ManagerManager: An error has occurred: Error - Syntax error, unrecognized expression: img[style:contains('cursor:help')]

Plus: the file mm_rules.inc.php is in russian language.

**Comment by TimGS** [comment]
The error with ManagerManager is noted in Issue 73 and will be fixed for release.

thanks,
Tim.
