### ISSUE TITLE
Manager Layout Issues

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#81]
A couple of layout issues with IE10 in the manager:

1) The text area boxes on System Configuration pages are either very near to right edge so scroll bar is only just visible or in the case of 'Interface & Features' TinyMCE Settings the text areas are not wrapping so are truncated at the edge of the browser window.

Same for 'ClipperCarbon' and 'ClipperModern' styles.

2) When editing a resource 'Menu index' plus and minus buttons are out of line, i.e. dropped down by nearly half a line. Seems to be an issue where buttons follow an input field as also an issue on 'Create/Edit Module' screen, 'General' tab for 'Icon (32x32)' field, for example.
Less so in 'ClipperCarbon' than 'ClipperModern' styles but still out of line.

**Comment by TimGS** [comment]
When comparing ClipperCarbon in Clipper 1.1 beta, and MODxCarbon in MODx Evo 1.0.6 or 1.0.7, do you see the same behaviour?

-- Tim.

**Comment by bossloper** [comment]
Looking at it again I think the old css must have been cached. It is fine now. I'll close this.
