### ISSUE TITLE
I could not find any use of the functions in media/script/datefunctions.js

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#93]
... so maybe it can be removed

**Comment by TimGS** [comment]
Its in docmanager, but perhaps with your jquery work this can be changed?

**Comment by Cipa** [comment]
Can you show me where. I looked in 1.1.develop and could not find it. Maybe the search functionality doesn't work as expected.

Thx

**Comment by TimGS** [comment]
assets/modules/docmanager/templates/main.tpl

Are you on linux or a mac? Use grep:

tim@dougal:~/varwww/ClipperCMS$ grep -ls -R datefunctions.js *
assets/modules/docmanager/templates/main.tpl

-- Tim.

## www.timspencerweb.co.uk

Better a bad day in the hills than a good day in the office.

## See the hills at www.islandlight.co.uk

**Comment by TimGS** [comment]
The JS maybe could be moved to assets/modules/docmanager/js?

**Comment by Cipa** [comment]
closed as docmanager is now called resmanager in the jquery-ui branch https://github.com/Cipa/ClipperCMS/tree/jquery-ui
