### ISSUE TITLE
Document Manager: document.range.submit(); errors

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#94]
Seems like document.range.submit(); generates js errors but the form is submitted.

TypeError: document.range is undefined
[Break On This Error]  
document.range.submit();

Weird thing is that without it the document doesn't submit. 
The only thing related is the <form id="range" action="" method="post"> in documents.tpl. There is no range unless it's a mootools variable that I could not find.

Any ideas on what could be causing this problem.

**Comment by TimGS** [comment]
Odd.

Is it using an obsolete shorthand for getting elements? I think for what it (might) be intending to do I'd use

document.getElementById('range').submit();

Try that.

**Comment by Cipa** [comment]
thx
