### ISSUE TITLE
Warning during Installation Upgrade from MODX 1.0.6

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#95]
During Installation Upgrade from MODX 1.0.6 (localhost XAMPP) I get this error (under Plugins, Install/Update TransAlias - 1.0.1):

Warning: in_array() expects parameter 2 to be array, boolean given in C:\xampp\htdocs\clippercms\install\action\action.options.php on line 176

**Comment by TimGS** [comment]
Can you test again with the latest version of 1.1.develop?

If all is fine, close this issue.

thanks,
Tim.
